"""Ordered, checksummed and transactional migrations for ERP foundations."""

from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib


def utc_now():
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


@dataclass(frozen=True)
class Migration:
    version: int
    name: str
    statements: tuple[str, ...]
    foreign_keys_off: bool = False

    @property
    def checksum(self):
        source = f"{self.version}:{self.name}\n" + "\n".join(self.statements)
        if self.foreign_keys_off:
            source += "\n#foreign_keys_off"
        return hashlib.sha256(source.encode("utf-8")).hexdigest()


MIGRATIONS = (
    Migration(1, "erp0_foundations", (
        """CREATE TABLE IF NOT EXISTS erp_command_log (
            id_command INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            command_name TEXT NOT NULL,
            idempotency_key TEXT NOT NULL,
            request_hash TEXT NOT NULL,
            status TEXT NOT NULL CHECK(status IN ('processing','completed')),
            response_json TEXT,
            actor_id INTEGER NOT NULL,
            actor_snapshot TEXT NOT NULL,
            origin TEXT NOT NULL,
            created_at_utc TEXT NOT NULL,
            completed_at_utc TEXT,
            UNIQUE(id_comunidad, command_name, idempotency_key),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(actor_id) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_audit_events (
            id_audit_event INTEGER PRIMARY KEY AUTOINCREMENT,
            event_id TEXT NOT NULL UNIQUE,
            id_comunidad INTEGER NOT NULL,
            actor_id INTEGER NOT NULL,
            actor_snapshot TEXT NOT NULL,
            action TEXT NOT NULL,
            entity_type TEXT NOT NULL,
            entity_id TEXT,
            before_json TEXT,
            after_json TEXT,
            reason TEXT,
            origin TEXT NOT NULL,
            request_id TEXT NOT NULL,
            entity_version INTEGER,
            occurred_at_utc TEXT NOT NULL,
            evidence_type TEXT,
            evidence_id TEXT,
            metadata_json TEXT,
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(actor_id) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_outbox (
            id_outbox INTEGER PRIMARY KEY AUTOINCREMENT,
            event_id TEXT NOT NULL UNIQUE,
            id_comunidad INTEGER NOT NULL,
            event_type TEXT NOT NULL,
            aggregate_type TEXT NOT NULL,
            aggregate_id TEXT,
            payload_json TEXT NOT NULL,
            dedupe_key TEXT NOT NULL,
            state TEXT NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','processing','processed','failed')),
            attempts INTEGER NOT NULL DEFAULT 0,
            available_at_utc TEXT NOT NULL,
            created_at_utc TEXT NOT NULL,
            processed_at_utc TEXT,
            last_error TEXT,
            UNIQUE(id_comunidad, event_type, dedupe_key),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_community_foundation (
            id_comunidad INTEGER PRIMARY KEY,
            foundation_status TEXT NOT NULL CHECK(foundation_status IN ('prepared','verified')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            updated_at_utc TEXT NOT NULL,
            updated_by INTEGER NOT NULL,
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(updated_by) REFERENCES usuarios(id_usuario)
        )""",
        "CREATE INDEX IF NOT EXISTS idx_erp_audit_community_entity ON erp_audit_events(id_comunidad,entity_type,entity_id,occurred_at_utc)",
        "CREATE INDEX IF NOT EXISTS idx_erp_audit_request ON erp_audit_events(request_id)",
        "CREATE INDEX IF NOT EXISTS idx_erp_outbox_pending ON erp_outbox(state,available_at_utc,id_outbox)",
        "CREATE INDEX IF NOT EXISTS idx_erp_command_actor ON erp_command_log(actor_id,created_at_utc)",
    )),
    Migration(2, "erp1_master_data", (
        "ALTER TABLE comunidades ADD COLUMN codigo TEXT",
        "ALTER TABLE comunidades ADD COLUMN denominacion TEXT",
        "ALTER TABLE comunidades ADD COLUMN nif TEXT",
        "ALTER TABLE comunidades ADD COLUMN domicilio TEXT",
        "ALTER TABLE comunidades ADD COLUMN contacto_administrativo TEXT",
        "ALTER TABLE comunidades ADD COLUMN zona_horaria TEXT NOT NULL DEFAULT 'Europe/Madrid'",
        "ALTER TABLE comunidades ADD COLUMN moneda TEXT NOT NULL DEFAULT 'EUR'",
        "ALTER TABLE comunidades ADD COLUMN estado_operativo TEXT NOT NULL DEFAULT 'activa' CHECK(estado_operativo IN ('preparacion','activa','suspendida','baja'))",
        "ALTER TABLE comunidades ADD COLUMN version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0)",
        "UPDATE comunidades SET codigo='COM-'||id_comunidad WHERE codigo IS NULL OR trim(codigo)=''",
        "UPDATE comunidades SET denominacion=nombre WHERE denominacion IS NULL OR trim(denominacion)=''",
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_comunidades_codigo ON comunidades(codigo) WHERE codigo IS NOT NULL",
        """CREATE TABLE IF NOT EXISTS erp_comunidad_config_versiones (
            id_config_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version > 0),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            configuracion_json TEXT NOT NULL DEFAULT '{}',
            estado TEXT NOT NULL DEFAULT 'vigente' CHECK(estado IN ('borrador','vigente','sustituida','anulada')),
            origen TEXT NOT NULL,
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            UNIQUE(id_comunidad,version),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_ejercicios (
            id_ejercicio INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            fecha_inicio TEXT NOT NULL,
            fecha_fin TEXT NOT NULL,
            moneda TEXT NOT NULL DEFAULT 'EUR',
            estado TEXT NOT NULL DEFAULT 'preparacion' CHECK(estado IN ('preparacion','abierto','cerrado')),
            fecha_apertura TEXT,
            abierto_por INTEGER,
            fecha_cierre TEXT,
            cerrado_por INTEGER,
            motivo TEXT,
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,codigo),
            UNIQUE(id_comunidad,id_ejercicio),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(abierto_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(cerrado_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario),
            CHECK(fecha_fin >= fecha_inicio)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_bloqueos_periodo (
            id_bloqueo INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_ejercicio INTEGER,
            dominio TEXT NOT NULL,
            fecha_inicio TEXT NOT NULL,
            fecha_fin TEXT NOT NULL,
            motivo TEXT NOT NULL,
            activo INTEGER NOT NULL DEFAULT 1 CHECK(activo IN (0,1)),
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            levantado_en TEXT,
            levantado_por INTEGER,
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            FOREIGN KEY(id_comunidad,id_ejercicio) REFERENCES erp_ejercicios(id_comunidad,id_ejercicio),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(levantado_por) REFERENCES usuarios(id_usuario),
            CHECK(fecha_fin >= fecha_inicio)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_agrupaciones (
            id_agrupacion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_padre INTEGER,
            codigo TEXT NOT NULL,
            nombre TEXT NOT NULL,
            tipo TEXT NOT NULL,
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('preparacion','activa','inactiva')),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,codigo),
            UNIQUE(id_comunidad,id_agrupacion),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(id_comunidad,id_padre) REFERENCES erp_agrupaciones(id_comunidad,id_agrupacion),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario),
            CHECK(id_padre IS NULL OR id_padre <> id_agrupacion),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_tipos_propiedad (
            id_tipo_propiedad INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            nombre TEXT NOT NULL,
            activo INTEGER NOT NULL DEFAULT 1 CHECK(activo IN (0,1)),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            creado_en TEXT NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,codigo),
            UNIQUE(id_comunidad,id_tipo_propiedad),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad)
        )""",
        "INSERT INTO erp_tipos_propiedad(id_comunidad,codigo,nombre,creado_en,origen) SELECT id_comunidad,'vivienda','Vivienda',CURRENT_TIMESTAMP,'erp1_migration' FROM comunidades",
        "INSERT INTO erp_tipos_propiedad(id_comunidad,codigo,nombre,creado_en,origen) SELECT id_comunidad,'local','Local',CURRENT_TIMESTAMP,'erp1_migration' FROM comunidades",
        "INSERT INTO erp_tipos_propiedad(id_comunidad,codigo,nombre,creado_en,origen) SELECT id_comunidad,'parcela','Parcela',CURRENT_TIMESTAMP,'erp1_migration' FROM comunidades",
        "INSERT INTO erp_tipos_propiedad(id_comunidad,codigo,nombre,creado_en,origen) SELECT id_comunidad,'garaje','Garaje',CURRENT_TIMESTAMP,'erp1_migration' FROM comunidades",
        "INSERT INTO erp_tipos_propiedad(id_comunidad,codigo,nombre,creado_en,origen) SELECT id_comunidad,'trastero','Trastero',CURRENT_TIMESTAMP,'erp1_migration' FROM comunidades",
        "INSERT INTO erp_tipos_propiedad(id_comunidad,codigo,nombre,creado_en,origen) SELECT id_comunidad,'otro','Otro',CURRENT_TIMESTAMP,'erp1_migration' FROM comunidades",
        "PRAGMA legacy_alter_table=ON",
        "ALTER TABLE cf_propiedades RENAME TO cf_propiedades_erp1_legacy",
        """CREATE TABLE cf_propiedades (
            id_propiedad INTEGER PRIMARY KEY AUTOINCREMENT,
            codigo_propiedad TEXT NOT NULL,
            codigo_normalizado TEXT NOT NULL,
            tipo_propiedad TEXT,
            zona TEXT,
            subzona TEXT,
            grupo TEXT,
            coeficiente REAL DEFAULT 0,
            activa INTEGER DEFAULT 1,
            fecha_creacion TEXT,
            fecha_ultima_actualizacion TEXT,
            id_importacion_origen INTEGER,
            id_comunidad INTEGER NOT NULL REFERENCES comunidades(id_comunidad),
            id_tipo_propiedad INTEGER,
            bloque TEXT,
            portal TEXT,
            planta TEXT,
            puerta TEXT,
            descripcion_direccion TEXT,
            referencia_registral TEXT,
            referencia_catastral TEXT,
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('preparacion','activa','inactiva','baja')),
            fecha_baja TEXT,
            motivo_baja TEXT,
            calidad_dato TEXT NOT NULL DEFAULT 'observada' CHECK(calidad_dato IN ('observada','pendiente_revision','validada')),
            origen_dato TEXT NOT NULL DEFAULT 'legacy',
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            UNIQUE(id_comunidad,codigo_normalizado),
            UNIQUE(id_comunidad,id_propiedad),
            FOREIGN KEY(id_importacion_origen) REFERENCES cf_importaciones_netfincas(id_importacion),
            FOREIGN KEY(id_comunidad,id_tipo_propiedad) REFERENCES erp_tipos_propiedad(id_comunidad,id_tipo_propiedad)
        )""",
        """INSERT INTO cf_propiedades(
            id_propiedad,codigo_propiedad,codigo_normalizado,tipo_propiedad,zona,subzona,grupo,coeficiente,
            activa,fecha_creacion,fecha_ultima_actualizacion,id_importacion_origen,id_comunidad,id_tipo_propiedad,
            estado,calidad_dato,origen_dato,version)
            SELECT p.id_propiedad,p.codigo_propiedad,p.codigo_normalizado,p.tipo_propiedad,p.zona,p.subzona,p.grupo,
            p.coeficiente,p.activa,p.fecha_creacion,p.fecha_ultima_actualizacion,p.id_importacion_origen,p.id_comunidad,
            COALESCE((SELECT t.id_tipo_propiedad FROM erp_tipos_propiedad t WHERE t.id_comunidad=p.id_comunidad AND t.codigo=CASE
                WHEN lower(COALESCE(p.tipo_propiedad,'')) LIKE '%garaj%' OR upper(p.codigo_propiedad) LIKE 'PLZ%' THEN 'garaje'
                WHEN lower(COALESCE(p.tipo_propiedad,'')) LIKE '%local%' THEN 'local'
                WHEN lower(COALESCE(p.tipo_propiedad,'')) LIKE '%parcela%' THEN 'parcela'
                WHEN lower(COALESCE(p.tipo_propiedad,'')) LIKE '%traster%' THEN 'trastero'
                WHEN lower(COALESCE(p.tipo_propiedad,'')) LIKE '%vivi%' THEN 'vivienda' ELSE 'otro' END),
            (SELECT t.id_tipo_propiedad FROM erp_tipos_propiedad t WHERE t.id_comunidad=p.id_comunidad AND t.codigo='otro')),
            CASE WHEN COALESCE(p.activa,1)=1 THEN 'activa' ELSE 'inactiva' END,'observada','legacy',1
            FROM cf_propiedades_erp1_legacy p""",
        "DROP TABLE cf_propiedades_erp1_legacy",
        "ALTER TABLE cf_propietarios RENAME TO cf_propietarios_erp1_legacy",
        """CREATE TABLE cf_propietarios (
            id_propietario INTEGER PRIMARY KEY AUTOINCREMENT,
            codigo_netfincas TEXT,
            nombre TEXT NOT NULL,
            nombre_normalizado TEXT,
            nif TEXT,
            direccion TEXT,
            cp TEXT,
            poblacion TEXT,
            provincia TEXT,
            activo INTEGER DEFAULT 1,
            fecha_creacion TEXT,
            fecha_ultima_actualizacion TEXT,
            id_importacion_origen INTEGER,
            id_comunidad INTEGER NOT NULL REFERENCES comunidades(id_comunidad),
            tipo_persona TEXT NOT NULL DEFAULT 'desconocida' CHECK(tipo_persona IN ('fisica','juridica','desconocida')),
            nombres TEXT,
            apellidos TEXT,
            razon_social TEXT,
            tipo_identificacion TEXT,
            pais_emisor TEXT,
            idioma_preferido TEXT,
            estado TEXT NOT NULL DEFAULT 'activo' CHECK(estado IN ('preparacion','activo','inactivo','baja')),
            calidad_identidad TEXT NOT NULL DEFAULT 'observada' CHECK(calidad_identidad IN ('observada','pendiente_desglosar','pendiente_revision','validada')),
            origen_dato TEXT NOT NULL DEFAULT 'legacy',
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            UNIQUE(id_comunidad,codigo_netfincas),
            UNIQUE(id_comunidad,id_propietario),
            FOREIGN KEY(id_importacion_origen) REFERENCES cf_importaciones_netfincas(id_importacion)
        )""",
        """INSERT INTO cf_propietarios(
            id_propietario,codigo_netfincas,nombre,nombre_normalizado,nif,direccion,cp,poblacion,provincia,activo,
            fecha_creacion,fecha_ultima_actualizacion,id_importacion_origen,id_comunidad,tipo_persona,estado,
            calidad_identidad,origen_dato,version)
            SELECT id_propietario,codigo_netfincas,nombre,nombre_normalizado,nif,direccion,cp,poblacion,provincia,activo,
            fecha_creacion,fecha_ultima_actualizacion,id_importacion_origen,id_comunidad,'desconocida',
            CASE WHEN COALESCE(activo,1)=1 THEN 'activo' ELSE 'inactivo' END,
            CASE WHEN instr(nombre,' / ')>0 OR instr(nombre,' & ')>0 THEN 'pendiente_desglosar' ELSE 'observada' END,
            'legacy',1 FROM cf_propietarios_erp1_legacy""",
        "DROP TABLE cf_propietarios_erp1_legacy",
        "PRAGMA legacy_alter_table=OFF",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN valor_normalizado TEXT",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN etiqueta TEXT",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN verificado INTEGER NOT NULL DEFAULT 0 CHECK(verificado IN (0,1))",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN uso_preferido TEXT",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN efectiva_desde TEXT",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN efectiva_hasta TEXT",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN procedencia TEXT NOT NULL DEFAULT 'legacy'",
        "ALTER TABLE cf_contactos_propietario ADD COLUMN version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0)",
        "UPDATE cf_contactos_propietario SET valor_normalizado=lower(trim(valor)) WHERE valor_normalizado IS NULL",
        "ALTER TABLE cf_propietario_propiedad ADD COLUMN porcentaje_titularidad_decimal TEXT",
        "ALTER TABLE cf_propietario_propiedad ADD COLUMN calidad TEXT NOT NULL DEFAULT 'observada' CHECK(calidad IN ('propuesta','pendiente_documentacion','observada','validada'))",
        "ALTER TABLE cf_propietario_propiedad ADD COLUMN procedencia TEXT NOT NULL DEFAULT 'legacy'",
        "ALTER TABLE cf_propietario_propiedad ADD COLUMN id_documento_evidencia INTEGER",
        "ALTER TABLE cf_propietario_propiedad ADD COLUMN fecha_conocimiento TEXT",
        "ALTER TABLE cf_propietario_propiedad ADD COLUMN version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0)",
        "UPDATE cf_propietario_propiedad SET porcentaje_titularidad_decimal=CAST(porcentaje_titularidad AS TEXT) WHERE porcentaje_titularidad_decimal IS NULL",
        """UPDATE cf_propietario_propiedad SET fecha_conocimiento=COALESCE(
            (SELECT i.fecha_importacion FROM cf_importaciones_netfincas i WHERE i.id_importacion=cf_propietario_propiedad.id_importacion_origen),
            CURRENT_TIMESTAMP) WHERE fecha_conocimiento IS NULL""",
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_cf_relacion_tenant_id ON cf_propietario_propiedad(id_comunidad,id_relacion)",
        """CREATE TABLE IF NOT EXISTS erp_propiedad_aliases (
            id_alias INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            alias TEXT NOT NULL,
            alias_normalizado TEXT NOT NULL,
            tipo TEXT NOT NULL DEFAULT 'busqueda',
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            activo INTEGER NOT NULL DEFAULT 1 CHECK(activo IN (0,1)),
            origen TEXT NOT NULL,
            creado_en TEXT NOT NULL,
            creado_por INTEGER,
            UNIQUE(id_comunidad,id_propiedad,alias_normalizado),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_propiedad_relaciones (
            id_relacion_propiedad INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propiedad_origen INTEGER NOT NULL,
            id_propiedad_destino INTEGER NOT NULL,
            tipo TEXT NOT NULL CHECK(tipo IN ('anexo','segregacion','agrupacion','otra')),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('propuesta','activa','inactiva')),
            motivo TEXT,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_propiedad_origen,id_propiedad_destino,tipo,efectiva_desde),
            FOREIGN KEY(id_comunidad,id_propiedad_origen) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(id_comunidad,id_propiedad_destino) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario),
            CHECK(id_propiedad_origen <> id_propiedad_destino),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_propiedad_agrupaciones (
            id_pertenencia INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            id_agrupacion INTEGER NOT NULL,
            rol TEXT NOT NULL DEFAULT 'estructural',
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            origen TEXT NOT NULL,
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            UNIQUE(id_comunidad,id_propiedad,id_agrupacion,rol,efectiva_desde),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(id_comunidad,id_agrupacion) REFERENCES erp_agrupaciones(id_comunidad,id_agrupacion),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_preferencias_comunicacion (
            id_preferencia INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propietario INTEGER NOT NULL,
            canal TEXT NOT NULL,
            idioma TEXT,
            id_contacto INTEGER,
            alcance TEXT,
            base_autorizacion TEXT,
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('propuesta','activa','inactiva')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            origen TEXT NOT NULL,
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            FOREIGN KEY(id_comunidad,id_propietario) REFERENCES cf_propietarios(id_comunidad,id_propietario),
            FOREIGN KEY(id_contacto) REFERENCES cf_contactos_propietario(id_contacto),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_titularidad_versiones (
            id_titularidad_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_relacion INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            id_propietario INTEGER NOT NULL,
            porcentaje_decimal TEXT,
            porcentaje_original TEXT,
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            calidad TEXT NOT NULL CHECK(calidad IN ('propuesta','pendiente_documentacion','observada','validada')),
            composicion_completa INTEGER NOT NULL DEFAULT 0 CHECK(composicion_completa IN (0,1)),
            anulada INTEGER NOT NULL DEFAULT 0 CHECK(anulada IN (0,1)),
            motivo TEXT,
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            id_importacion INTEGER,
            fila_origen TEXT,
            id_version_sustituida INTEGER,
            id_operacion TEXT NOT NULL,
            version_concurrencia INTEGER NOT NULL DEFAULT 1 CHECK(version_concurrencia > 0),
            UNIQUE(id_relacion,version_concurrencia),
            UNIQUE(id_comunidad,id_titularidad_version),
            FOREIGN KEY(id_comunidad,id_relacion) REFERENCES cf_propietario_propiedad(id_comunidad,id_relacion),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(id_comunidad,id_propietario) REFERENCES cf_propietarios(id_comunidad,id_propietario),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(id_importacion) REFERENCES cf_importaciones_netfincas(id_importacion),
            FOREIGN KEY(id_version_sustituida) REFERENCES erp_titularidad_versiones(id_titularidad_version),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """INSERT INTO erp_titularidad_versiones(
            id_comunidad,id_relacion,id_propiedad,id_propietario,porcentaje_decimal,porcentaje_original,
            efectiva_desde,efectiva_hasta,calidad,composicion_completa,motivo,registrada_en,registrada_por,
            origen,id_importacion,id_operacion,version_concurrencia)
            SELECT r.id_comunidad,r.id_relacion,r.id_propiedad,r.id_propietario,r.porcentaje_titularidad_decimal,
            CAST(r.porcentaje_titularidad AS TEXT),NULLIF(trim(r.fecha_desde),''),NULLIF(trim(r.fecha_hasta),''),'observada',
            CASE WHEN r.porcentaje_titularidad_decimal='100.0' OR r.porcentaje_titularidad_decimal='100' THEN 1 ELSE 0 END,
            r.motivo,COALESCE(r.fecha_conocimiento,CURRENT_TIMESTAMP),
            COALESCE((SELECT MIN(id_usuario) FROM usuarios WHERE activo=1),1),'legacy',r.id_importacion_origen,
            'ERP1-MIGRATION-'||r.id_relacion,1 FROM cf_propietario_propiedad r""",
        """CREATE TABLE IF NOT EXISTS erp_titularidad_propuestas (
            id_propuesta INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            efectiva_desde TEXT,
            fecha_conocimiento TEXT NOT NULL,
            calidad TEXT NOT NULL CHECK(calidad IN ('pendiente_documentacion','observada','validada')),
            composicion_completa INTEGER NOT NULL CHECK(composicion_completa IN (0,1)),
            estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','confirmada','cancelada')),
            motivo TEXT,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            confirmada_en TEXT,
            confirmada_por INTEGER,
            id_operacion TEXT,
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(confirmada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_titularidad_propuesta_lineas (
            id_linea INTEGER PRIMARY KEY AUTOINCREMENT,
            id_propuesta INTEGER NOT NULL,
            id_propietario INTEGER NOT NULL,
            porcentaje_decimal TEXT,
            porcentaje_original TEXT,
            calidad TEXT NOT NULL CHECK(calidad IN ('pendiente_documentacion','observada','validada')),
            UNIQUE(id_propuesta,id_propietario),
            FOREIGN KEY(id_propuesta) REFERENCES erp_titularidad_propuestas(id_propuesta) ON DELETE CASCADE,
            FOREIGN KEY(id_propietario) REFERENCES cf_propietarios(id_propietario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_grupos_reparto (
            id_grupo INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            nombre TEXT NOT NULL,
            finalidad TEXT,
            estado TEXT NOT NULL DEFAULT 'preparacion' CHECK(estado IN ('preparacion','activo','inactivo')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,codigo),
            UNIQUE(id_comunidad,id_grupo),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_grupo_versiones (
            id_grupo_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_grupo INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version > 0),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            base TEXT NOT NULL CHECK(base IN ('porcentaje','peso','sin_coeficiente','otra')),
            suma_esperada_decimal TEXT,
            tolerancia_importacion_decimal TEXT,
            criterio_documental TEXT,
            estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','observada','aprobada','sustituida','anulada')),
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_grupo,version),
            FOREIGN KEY(id_comunidad,id_grupo) REFERENCES erp_grupos_reparto(id_comunidad,id_grupo),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_grupo_miembros (
            id_miembro INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_grupo INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_grupo,id_propiedad),
            UNIQUE(id_comunidad,id_miembro),
            FOREIGN KEY(id_comunidad,id_grupo) REFERENCES erp_grupos_reparto(id_comunidad,id_grupo),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_grupo_miembro_versiones (
            id_miembro_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_miembro INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version > 0),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            participa INTEGER NOT NULL CHECK(participa IN (0,1)),
            excluida INTEGER NOT NULL DEFAULT 0 CHECK(excluida IN (0,1)),
            motivo TEXT,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_miembro,version),
            FOREIGN KEY(id_comunidad,id_miembro) REFERENCES erp_grupo_miembros(id_comunidad,id_miembro),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            CHECK(NOT(participa=1 AND excluida=1)),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_coeficiente_series (
            id_serie INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            id_grupo INTEGER,
            finalidad TEXT NOT NULL,
            unidad TEXT NOT NULL CHECK(unidad IN ('porcentaje','tanto_por_uno','peso','otra')),
            escala INTEGER NOT NULL DEFAULT 12 CHECK(escala >= 0 AND escala <= 30),
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('preparacion','activa','inactiva')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version > 0),
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_propiedad,id_grupo,finalidad,unidad),
            UNIQUE(id_comunidad,id_serie),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(id_comunidad,id_grupo) REFERENCES erp_grupos_reparto(id_comunidad,id_grupo),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_coeficiente_versiones (
            id_coeficiente_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_serie INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version > 0),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            valor_decimal TEXT NOT NULL,
            valor_original TEXT,
            precision_original INTEGER,
            calidad TEXT NOT NULL CHECK(calidad IN ('pendiente_documentacion','observada','validada')),
            estado TEXT NOT NULL DEFAULT 'observada' CHECK(estado IN ('borrador','observada','aprobada','sustituida','anulada')),
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            id_importacion INTEGER,
            fila_origen TEXT,
            id_version_sustituida INTEGER,
            UNIQUE(id_serie,version),
            FOREIGN KEY(id_comunidad,id_serie) REFERENCES erp_coeficiente_series(id_comunidad,id_serie),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(id_importacion) REFERENCES cf_importaciones_netfincas(id_importacion),
            FOREIGN KEY(id_version_sustituida) REFERENCES erp_coeficiente_versiones(id_coeficiente_version),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta > efectiva_desde)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_fuente_registros (
            id_fuente_registro INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            sistema_origen TEXT NOT NULL,
            entidad_origen TEXT NOT NULL,
            codigo_origen TEXT,
            id_importacion INTEGER,
            fila_origen TEXT,
            campo_origen TEXT,
            valor_original TEXT,
            entidad_destino TEXT NOT NULL,
            id_destino TEXT NOT NULL,
            decision TEXT NOT NULL,
            incidencia TEXT,
            resolucion TEXT,
            hash_hecho TEXT NOT NULL,
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            UNIQUE(id_comunidad,sistema_origen,hash_hecho),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(id_importacion) REFERENCES cf_importaciones_netfincas(id_importacion),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE IF NOT EXISTS erp_master_document_links (
            id_enlace INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            entidad_tipo TEXT NOT NULL,
            entidad_id TEXT NOT NULL,
            documento_tipo TEXT NOT NULL,
            documento_id TEXT NOT NULL,
            finalidad TEXT,
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,entidad_tipo,entidad_id,documento_tipo,documento_id,finalidad),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """INSERT INTO erp_grupos_reparto(id_comunidad,codigo,nombre,finalidad,estado,creado_en,creado_por,origen)
            SELECT DISTINCT p.id_comunidad,'LEGACY_GENERAL','Coeficiente general importado (sin validar)',
            'compatibilidad de coeficientes históricos','preparacion',CURRENT_TIMESTAMP,
            COALESCE((SELECT MIN(id_usuario) FROM usuarios WHERE activo=1),1),'erp1_migration'
            FROM cf_propiedades p WHERE p.coeficiente IS NOT NULL""",
        """INSERT INTO erp_grupo_versiones(id_comunidad,id_grupo,version,base,suma_esperada_decimal,
            estado,criterio_documental,registrada_en,registrada_por,origen)
            SELECT g.id_comunidad,g.id_grupo,1,'porcentaje',NULL,'observada',
            'Origen REAL legacy; requiere contraste con documento fuente',CURRENT_TIMESTAMP,g.creado_por,'erp1_migration'
            FROM erp_grupos_reparto g WHERE g.codigo='LEGACY_GENERAL'""",
        """INSERT INTO erp_grupo_miembros(id_comunidad,id_grupo,id_propiedad,creado_en,creado_por,origen)
            SELECT p.id_comunidad,g.id_grupo,p.id_propiedad,CURRENT_TIMESTAMP,g.creado_por,'erp1_migration'
            FROM cf_propiedades p JOIN erp_grupos_reparto g ON g.id_comunidad=p.id_comunidad AND g.codigo='LEGACY_GENERAL'""",
        """INSERT INTO erp_grupo_miembro_versiones(id_comunidad,id_miembro,version,participa,excluida,
            registrada_en,registrada_por,origen)
            SELECT m.id_comunidad,m.id_miembro,1,1,0,CURRENT_TIMESTAMP,m.creado_por,'erp1_migration'
            FROM erp_grupo_miembros m""",
        """INSERT INTO erp_coeficiente_series(id_comunidad,id_propiedad,id_grupo,finalidad,unidad,escala,
            estado,creada_en,creada_por,origen)
            SELECT p.id_comunidad,p.id_propiedad,g.id_grupo,'general_legacy','porcentaje',12,'preparacion',
            CURRENT_TIMESTAMP,g.creado_por,'erp1_migration'
            FROM cf_propiedades p JOIN erp_grupos_reparto g ON g.id_comunidad=p.id_comunidad AND g.codigo='LEGACY_GENERAL'
            WHERE p.coeficiente IS NOT NULL""",
        """INSERT INTO erp_coeficiente_versiones(id_comunidad,id_serie,version,valor_decimal,valor_original,
            precision_original,calidad,estado,registrada_en,registrada_por,origen,id_importacion)
            SELECT s.id_comunidad,s.id_serie,1,CAST(p.coeficiente AS TEXT),CAST(p.coeficiente AS TEXT),NULL,
            'observada','observada',CURRENT_TIMESTAMP,s.creada_por,'legacy',p.id_importacion_origen
            FROM erp_coeficiente_series s JOIN cf_propiedades p ON p.id_propiedad=s.id_propiedad""",
        "CREATE INDEX IF NOT EXISTS idx_erp_ejercicios_periodo ON erp_ejercicios(id_comunidad,fecha_inicio,fecha_fin,estado)",
        "CREATE INDEX IF NOT EXISTS idx_erp_agrupaciones_padre ON erp_agrupaciones(id_comunidad,id_padre)",
        "CREATE INDEX IF NOT EXISTS idx_cf_propiedades_busqueda ON cf_propiedades(id_comunidad,codigo_normalizado,estado)",
        "CREATE INDEX IF NOT EXISTS idx_cf_propietarios_busqueda ON cf_propietarios(id_comunidad,nombre_normalizado,estado)",
        "CREATE INDEX IF NOT EXISTS idx_cf_contactos_normalizado ON cf_contactos_propietario(id_comunidad,tipo,valor_normalizado)",
        "CREATE INDEX IF NOT EXISTS idx_erp_titularidad_temporal ON erp_titularidad_versiones(id_comunidad,id_propiedad,efectiva_desde,efectiva_hasta,registrada_en)",
        "CREATE INDEX IF NOT EXISTS idx_erp_coeficiente_temporal ON erp_coeficiente_versiones(id_comunidad,id_serie,efectiva_desde,efectiva_hasta)",
        "CREATE INDEX IF NOT EXISTS idx_erp_grupo_miembro_temporal ON erp_grupo_miembro_versiones(id_comunidad,id_miembro,efectiva_desde,efectiva_hasta)",
        "CREATE INDEX IF NOT EXISTS idx_erp_fuente_destino ON erp_fuente_registros(id_comunidad,entidad_destino,id_destino)",
    ), True),
    Migration(3, "erp2a_budget_foundations", (
        """CREATE TABLE erp_presupuesto_permisos (
            id_usuario INTEGER NOT NULL,
            id_comunidad INTEGER NOT NULL,
            puede_ver INTEGER NOT NULL DEFAULT 0 CHECK(puede_ver IN (0,1)),
            puede_preparar INTEGER NOT NULL DEFAULT 0 CHECK(puede_preparar IN (0,1)),
            puede_aprobar INTEGER NOT NULL DEFAULT 0 CHECK(puede_aprobar IN (0,1)),
            puede_configurar_cobro INTEGER NOT NULL DEFAULT 0 CHECK(puede_configurar_cobro IN (0,1)),
            activo INTEGER NOT NULL DEFAULT 1 CHECK(activo IN (0,1)),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            actualizado_en TEXT NOT NULL,
            actualizado_por INTEGER NOT NULL,
            PRIMARY KEY(id_usuario,id_comunidad),
            FOREIGN KEY(id_usuario) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(actualizado_por) REFERENCES usuarios(id_usuario)
        )""",
        """INSERT INTO erp_presupuesto_permisos(id_usuario,id_comunidad,puede_ver,puede_preparar,puede_aprobar,puede_configurar_cobro,actualizado_en,actualizado_por)
            SELECT p.id_usuario,p.id_comunidad,p.puede_ver,p.puede_actualizar,
                   CASE WHEN p.rol_en_comunidad IN ('Superusuario','Administrador') AND p.puede_actualizar=1 THEN 1 ELSE 0 END,
                   CASE WHEN p.rol_en_comunidad IN ('Superusuario','Administrador') AND p.puede_actualizar=1 THEN 1 ELSE 0 END,
                   CURRENT_TIMESTAMP,p.id_usuario
            FROM usuario_comunidad_permisos p WHERE p.activo=1""",
        """CREATE TABLE erp_reglas_reparto (
            id_regla INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            nombre TEXT NOT NULL,
            tipo TEXT NOT NULL CHECK(tipo IN ('coeficiente','partes_iguales','importe_fijo','unidades','consumo','porcentaje_especial','mixta')),
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('preparacion','activa','inactiva')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,codigo),
            UNIQUE(id_comunidad,id_regla),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_regla_versiones (
            id_regla_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_regla INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version>0),
            codigo_motor TEXT NOT NULL,
            version_motor TEXT NOT NULL,
            parametros_json TEXT NOT NULL DEFAULT '{}',
            esquema_parametros_json TEXT NOT NULL DEFAULT '{}',
            estado TEXT NOT NULL CHECK(estado IN ('borrador','aprobada','sustituida','anulada')),
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            UNIQUE(id_regla,version),
            UNIQUE(id_comunidad,id_regla_version),
            FOREIGN KEY(id_comunidad,id_regla) REFERENCES erp_reglas_reparto(id_comunidad,id_regla),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_regla_componentes (
            id_componente INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_regla_version INTEGER NOT NULL,
            id_subregla_version INTEGER NOT NULL,
            modo TEXT NOT NULL CHECK(modo IN ('importe','porcentaje')),
            valor_decimal TEXT NOT NULL,
            orden INTEGER NOT NULL CHECK(orden>=0),
            UNIQUE(id_regla_version,orden),
            FOREIGN KEY(id_comunidad,id_regla_version) REFERENCES erp_regla_versiones(id_comunidad,id_regla_version),
            FOREIGN KEY(id_comunidad,id_subregla_version) REFERENCES erp_regla_versiones(id_comunidad,id_regla_version),
            CHECK(id_regla_version<>id_subregla_version)
        )""",
        """CREATE TABLE erp_presupuestos (
            id_presupuesto INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_ejercicio INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            denominacion TEXT NOT NULL,
            tipo TEXT NOT NULL DEFAULT 'ordinario' CHECK(tipo IN ('ordinario')),
            moneda TEXT NOT NULL DEFAULT 'EUR',
            estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','propuesto','aprobado','cerrado','archivado')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,codigo),
            UNIQUE(id_comunidad,id_presupuesto),
            FOREIGN KEY(id_comunidad,id_ejercicio) REFERENCES erp_ejercicios(id_comunidad,id_ejercicio),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_presupuesto_versiones (
            id_presupuesto_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_presupuesto INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version>0),
            fecha_inicio TEXT NOT NULL,
            fecha_fin TEXT NOT NULL,
            periodicidad TEXT NOT NULL CHECK(periodicidad IN ('mensual','trimestral','semestral','anual')),
            dia_emision_previsto INTEGER CHECK(dia_emision_previsto BETWEEN 1 AND 31),
            dia_vencimiento INTEGER CHECK(dia_vencimiento BETWEEN 1 AND 31),
            id_version_origen INTEGER,
            estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','propuesta','aprobada','sustituida','anulada')),
            version_concurrencia INTEGER NOT NULL DEFAULT 1 CHECK(version_concurrencia>0),
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_presupuesto,version),
            UNIQUE(id_comunidad,id_presupuesto_version),
            FOREIGN KEY(id_comunidad,id_presupuesto) REFERENCES erp_presupuestos(id_comunidad,id_presupuesto),
            FOREIGN KEY(id_version_origen) REFERENCES erp_presupuesto_versiones(id_presupuesto_version),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            CHECK(fecha_fin>=fecha_inicio)
        )""",
        """CREATE TABLE erp_presupuesto_capitulos (
            id_capitulo INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_presupuesto_version INTEGER NOT NULL,
            clave_continuidad TEXT NOT NULL,
            codigo TEXT,
            nombre TEXT NOT NULL,
            descripcion TEXT,
            orden INTEGER NOT NULL CHECK(orden>=0),
            UNIQUE(id_presupuesto_version,clave_continuidad),
            UNIQUE(id_presupuesto_version,orden),
            UNIQUE(id_comunidad,id_capitulo),
            FOREIGN KEY(id_comunidad,id_presupuesto_version) REFERENCES erp_presupuesto_versiones(id_comunidad,id_presupuesto_version)
        )""",
        """CREATE TABLE erp_presupuesto_partidas (
            id_partida INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_presupuesto_version INTEGER NOT NULL,
            id_capitulo INTEGER NOT NULL,
            clave_continuidad TEXT NOT NULL,
            codigo TEXT,
            concepto TEXT NOT NULL,
            descripcion TEXT,
            importe_centimos INTEGER NOT NULL CHECK(importe_centimos>=0),
            orden INTEGER NOT NULL CHECK(orden>=0),
            categoria_origen TEXT,
            referencia_pgc TEXT,
            UNIQUE(id_presupuesto_version,clave_continuidad),
            UNIQUE(id_capitulo,orden),
            UNIQUE(id_comunidad,id_partida),
            FOREIGN KEY(id_comunidad,id_presupuesto_version) REFERENCES erp_presupuesto_versiones(id_comunidad,id_presupuesto_version),
            FOREIGN KEY(id_comunidad,id_capitulo) REFERENCES erp_presupuesto_capitulos(id_comunidad,id_capitulo)
        )""",
        """CREATE TABLE erp_partida_repartos (
            id_asignacion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_partida INTEGER NOT NULL,
            clave_linea TEXT NOT NULL,
            id_grupo INTEGER NOT NULL,
            id_grupo_version INTEGER NOT NULL,
            finalidad_serie TEXT,
            unidad_serie TEXT,
            id_regla_version INTEGER NOT NULL,
            modo TEXT NOT NULL CHECK(modo IN ('importe','porcentaje')),
            valor_decimal TEXT NOT NULL,
            orden INTEGER NOT NULL CHECK(orden>=0),
            UNIQUE(id_partida,clave_linea),
            UNIQUE(id_partida,orden),
            UNIQUE(id_comunidad,id_asignacion),
            FOREIGN KEY(id_comunidad,id_partida) REFERENCES erp_presupuesto_partidas(id_comunidad,id_partida),
            FOREIGN KEY(id_comunidad,id_grupo) REFERENCES erp_grupos_reparto(id_comunidad,id_grupo),
            FOREIGN KEY(id_grupo_version) REFERENCES erp_grupo_versiones(id_grupo_version),
            FOREIGN KEY(id_comunidad,id_regla_version) REFERENCES erp_regla_versiones(id_comunidad,id_regla_version)
        )""",
        """CREATE TABLE erp_partida_financiaciones (
            id_financiacion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_partida INTEGER NOT NULL,
            tipo_fuente TEXT NOT NULL CHECK(tipo_fuente IN ('cuotas','fondos_propios','otro_ingreso')),
            importe_centimos INTEGER NOT NULL CHECK(importe_centimos>=0),
            descripcion TEXT,
            estado_revision TEXT NOT NULL CHECK(estado_revision IN ('pendiente','confirmada')),
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            UNIQUE(id_comunidad,id_financiacion),
            FOREIGN KEY(id_comunidad,id_partida) REFERENCES erp_presupuesto_partidas(id_comunidad,id_partida)
        )""",
        """CREATE TABLE erp_partida_exenciones (
            id_exencion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_partida INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            tratamiento TEXT NOT NULL CHECK(tratamiento IN ('redistribuir','otra_financiacion')),
            motivo TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('activa','finalizada','anulada')),
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_exencion),
            FOREIGN KEY(id_comunidad,id_partida) REFERENCES erp_presupuesto_partidas(id_comunidad,id_partida),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta>efectiva_desde)
        )""",
        """CREATE TABLE erp_simulaciones (
            id_simulacion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_presupuesto_version INTEGER,
            origen_tipo TEXT NOT NULL CHECK(origen_tipo IN ('presupuesto','derrama','regularizacion')),
            origen_id TEXT NOT NULL,
            hash_entradas TEXT NOT NULL,
            version_motor TEXT NOT NULL,
            version_redondeo TEXT NOT NULL,
            fecha_referencia TEXT NOT NULL,
            conocida_en TEXT NOT NULL,
            moneda TEXT NOT NULL,
            estado TEXT NOT NULL CHECK(estado IN ('pendiente','calculando','completa','fallida','obsoleta')),
            importe_objetivo_centimos INTEGER NOT NULL,
            importe_resultado_centimos INTEGER,
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            completada_en TEXT,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,hash_entradas,version_motor),
            UNIQUE(id_comunidad,id_simulacion),
            FOREIGN KEY(id_comunidad,id_presupuesto_version) REFERENCES erp_presupuesto_versiones(id_comunidad,id_presupuesto_version),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_simulacion_entradas (
            id_entrada INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_simulacion INTEGER NOT NULL,
            tipo TEXT NOT NULL,
            clave TEXT NOT NULL,
            referencia_id TEXT,
            version_referencia INTEGER,
            valor_json TEXT NOT NULL,
            hash_valor TEXT NOT NULL,
            UNIQUE(id_simulacion,tipo,clave),
            FOREIGN KEY(id_comunidad,id_simulacion) REFERENCES erp_simulaciones(id_comunidad,id_simulacion)
        )""",
        """CREATE TABLE erp_calculo_lineas (
            id_calculo_linea INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_simulacion INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            id_capitulo INTEGER,
            id_partida INTEGER,
            id_asignacion INTEGER,
            id_grupo_version INTEGER,
            id_miembro_version INTEGER,
            id_serie INTEGER,
            id_coeficiente_version INTEGER,
            id_regla_version INTEGER NOT NULL,
            valor_decimal TEXT,
            denominador_decimal TEXT,
            numerador_exacto TEXT NOT NULL,
            denominador_exacto TEXT NOT NULL,
            importe_base_centimos INTEGER NOT NULL,
            ajuste_redondeo_centimos INTEGER NOT NULL DEFAULT 0,
            importe_final_centimos INTEGER NOT NULL,
            orden_desempate TEXT NOT NULL,
            UNIQUE(id_simulacion,id_propiedad,id_partida,id_asignacion),
            UNIQUE(id_comunidad,id_calculo_linea),
            FOREIGN KEY(id_comunidad,id_simulacion) REFERENCES erp_simulaciones(id_comunidad,id_simulacion),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(id_comunidad,id_regla_version) REFERENCES erp_regla_versiones(id_comunidad,id_regla_version)
        )""",
        """CREATE TABLE erp_plan_periodos (
            id_periodo_plan INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_plan_version INTEGER NOT NULL,
            clave_periodo TEXT NOT NULL,
            fecha_inicio TEXT NOT NULL,
            fecha_fin TEXT NOT NULL,
            fecha_emision_prevista TEXT,
            fecha_vencimiento TEXT,
            peso_decimal TEXT NOT NULL DEFAULT '1',
            id_ejercicio INTEGER NOT NULL,
            orden INTEGER NOT NULL CHECK(orden>=0),
            UNIQUE(id_plan_version,clave_periodo),
            UNIQUE(id_plan_version,orden),
            UNIQUE(id_comunidad,id_periodo_plan),
            CHECK(fecha_fin>=fecha_inicio),
            FOREIGN KEY(id_comunidad,id_plan_version) REFERENCES erp_plan_versiones(id_comunidad,id_plan_version),
            FOREIGN KEY(id_comunidad,id_ejercicio) REFERENCES erp_ejercicios(id_comunidad,id_ejercicio)
        )""",
        """CREATE TABLE erp_calculo_periodos (
            id_calculo_periodo INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_calculo_linea INTEGER NOT NULL,
            id_periodo_plan INTEGER NOT NULL,
            numerador_exacto TEXT NOT NULL,
            denominador_exacto TEXT NOT NULL,
            importe_base_centimos INTEGER NOT NULL,
            ajuste_redondeo_centimos INTEGER NOT NULL DEFAULT 0,
            importe_final_centimos INTEGER NOT NULL,
            UNIQUE(id_calculo_linea,id_periodo_plan),
            FOREIGN KEY(id_comunidad,id_calculo_linea) REFERENCES erp_calculo_lineas(id_comunidad,id_calculo_linea),
            FOREIGN KEY(id_comunidad,id_periodo_plan) REFERENCES erp_plan_periodos(id_comunidad,id_periodo_plan)
        )""",
        """CREATE TABLE erp_calculo_incidencias (
            id_incidencia INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_simulacion INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            severidad TEXT NOT NULL CHECK(severidad IN ('error','advertencia','preparacion_cobro')),
            entidad_tipo TEXT,
            entidad_id TEXT,
            campo TEXT,
            mensaje TEXT NOT NULL,
            solucion TEXT,
            reconocida_en TEXT,
            reconocida_por INTEGER,
            motivo_reconocimiento TEXT,
            FOREIGN KEY(id_comunidad,id_simulacion) REFERENCES erp_simulaciones(id_comunidad,id_simulacion),
            FOREIGN KEY(reconocida_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_planes_cuota (
            id_plan INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            tipo TEXT NOT NULL CHECK(tipo IN ('ordinario','derrama','regularizacion','ajuste')),
            origen_tipo TEXT NOT NULL,
            origen_id TEXT NOT NULL,
            moneda TEXT NOT NULL,
            estado TEXT NOT NULL CHECK(estado IN ('borrador','aprobado','cerrado','cancelado')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,tipo,origen_tipo,origen_id),
            UNIQUE(id_comunidad,id_plan),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_plan_versiones (
            id_plan_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_plan INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version>0),
            id_simulacion INTEGER NOT NULL,
            fecha_inicio TEXT NOT NULL,
            fecha_fin TEXT NOT NULL,
            estado TEXT NOT NULL CHECK(estado IN ('borrador','aprobada','sustituida','anulada')),
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_plan,version),
            UNIQUE(id_comunidad,id_plan_version),
            FOREIGN KEY(id_comunidad,id_plan) REFERENCES erp_planes_cuota(id_comunidad,id_plan),
            FOREIGN KEY(id_comunidad,id_simulacion) REFERENCES erp_simulaciones(id_comunidad,id_simulacion),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            CHECK(fecha_fin>=fecha_inicio)
        )""",
        """CREATE TABLE erp_presupuesto_actos (
            id_acto INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_presupuesto INTEGER NOT NULL,
            id_presupuesto_version INTEGER NOT NULL,
            id_simulacion INTEGER,
            id_plan_version INTEGER,
            tipo TEXT NOT NULL CHECK(tipo IN ('proponer','aprobar','cerrar','archivar','sustituir')),
            hash_contenido TEXT NOT NULL,
            fecha_acuerdo TEXT,
            motivo TEXT,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            registrado_en TEXT NOT NULL,
            registrado_por INTEGER NOT NULL,
            UNIQUE(id_presupuesto_version,tipo,hash_contenido),
            FOREIGN KEY(id_comunidad,id_presupuesto) REFERENCES erp_presupuestos(id_comunidad,id_presupuesto),
            FOREIGN KEY(id_comunidad,id_presupuesto_version) REFERENCES erp_presupuesto_versiones(id_comunidad,id_presupuesto_version),
            FOREIGN KEY(id_comunidad,id_simulacion) REFERENCES erp_simulaciones(id_comunidad,id_simulacion),
            FOREIGN KEY(id_comunidad,id_plan_version) REFERENCES erp_plan_versiones(id_comunidad,id_plan_version),
            FOREIGN KEY(registrado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_presupuesto_correspondencias (
            id_correspondencia INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_partida_origen INTEGER NOT NULL,
            id_partida_destino INTEGER NOT NULL,
            tipo TEXT NOT NULL CHECK(tipo IN ('copia','continuidad','division','fusion')),
            confirmada_en TEXT NOT NULL,
            confirmada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_partida_origen,id_partida_destino,tipo),
            FOREIGN KEY(id_comunidad,id_partida_origen) REFERENCES erp_presupuesto_partidas(id_comunidad,id_partida),
            FOREIGN KEY(id_comunidad,id_partida_destino) REFERENCES erp_presupuesto_partidas(id_comunidad,id_partida),
            FOREIGN KEY(confirmada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_plan_sucesiones (
            id_sucesion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_plan_origen INTEGER NOT NULL,
            id_plan_destino INTEGER NOT NULL,
            concepto TEXT NOT NULL,
            fecha_desde TEXT NOT NULL,
            motivo TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            registrado_en TEXT NOT NULL,
            registrado_por INTEGER NOT NULL,
            UNIQUE(id_plan_origen,id_plan_destino,fecha_desde),
            FOREIGN KEY(id_comunidad,id_plan_origen) REFERENCES erp_planes_cuota(id_comunidad,id_plan),
            FOREIGN KEY(id_comunidad,id_plan_destino) REFERENCES erp_planes_cuota(id_comunidad,id_plan),
            FOREIGN KEY(registrado_por) REFERENCES usuarios(id_usuario),
            CHECK(id_plan_origen<>id_plan_destino)
        )""",
        """CREATE TABLE erp_derramas (
            id_derrama INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            concepto TEXT NOT NULL,
            importe_centimos INTEGER NOT NULL CHECK(importe_centimos>=0),
            moneda TEXT NOT NULL DEFAULT 'EUR',
            estado TEXT NOT NULL DEFAULT 'borrador' CHECK(estado IN ('borrador','propuesta','aprobada','cerrada','cancelada')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            fecha_aprobacion TEXT,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,codigo),
            UNIQUE(id_comunidad,id_derrama),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_derrama_repartos (
            id_reparto INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_derrama INTEGER NOT NULL,
            id_grupo INTEGER NOT NULL,
            id_grupo_version INTEGER NOT NULL,
            finalidad_serie TEXT,
            unidad_serie TEXT,
            id_regla_version INTEGER NOT NULL,
            modo TEXT NOT NULL CHECK(modo IN ('importe','porcentaje')),
            valor_decimal TEXT NOT NULL,
            orden INTEGER NOT NULL CHECK(orden>=0),
            UNIQUE(id_derrama,orden),
            FOREIGN KEY(id_comunidad,id_derrama) REFERENCES erp_derramas(id_comunidad,id_derrama),
            FOREIGN KEY(id_comunidad,id_grupo) REFERENCES erp_grupos_reparto(id_comunidad,id_grupo),
            FOREIGN KEY(id_grupo_version) REFERENCES erp_grupo_versiones(id_grupo_version),
            FOREIGN KEY(id_comunidad,id_regla_version) REFERENCES erp_regla_versiones(id_comunidad,id_regla_version)
        )""",
        """CREATE TABLE erp_regularizaciones (
            id_regularizacion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_plan_esperado INTEGER NOT NULL,
            fecha_corte TEXT NOT NULL,
            conocida_en TEXT NOT NULL,
            cobertura_desde TEXT,
            cobertura_hasta TEXT,
            motivo TEXT NOT NULL,
            estado TEXT NOT NULL CHECK(estado IN ('borrador','calculada','aprobada','emitida','cancelada')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_regularizacion),
            FOREIGN KEY(id_comunidad,id_plan_esperado) REFERENCES erp_planes_cuota(id_comunidad,id_plan),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_regularizacion_lineas (
            id_linea INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_regularizacion INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            concepto_clave TEXT NOT NULL,
            periodo_clave TEXT NOT NULL,
            debido_centimos INTEGER NOT NULL,
            emitido_neto_centimos INTEGER NOT NULL,
            cobrado_centimos INTEGER NOT NULL DEFAULT 0,
            ajustes_previos_centimos INTEGER NOT NULL DEFAULT 0,
            diferencia_centimos INTEGER NOT NULL,
            estado_destinatario TEXT NOT NULL DEFAULT 'pendiente' CHECK(estado_destinatario IN ('pendiente','confirmado','no_aplica')),
            UNIQUE(id_regularizacion,id_propiedad,concepto_clave,periodo_clave),
            UNIQUE(id_comunidad,id_linea),
            FOREIGN KEY(id_comunidad,id_regularizacion) REFERENCES erp_regularizaciones(id_comunidad,id_regularizacion),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            CHECK(diferencia_centimos=debido_centimos-emitido_neto_centimos-ajustes_previos_centimos)
        )""",
        """CREATE TABLE erp_regularizacion_origenes (
            id_origen INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_linea INTEGER NOT NULL,
            sistema TEXT NOT NULL,
            tipo TEXT NOT NULL CHECK(tipo IN ('cargo','abono','ajuste')),
            referencia TEXT NOT NULL,
            importe_centimos INTEGER NOT NULL,
            snapshot_json TEXT NOT NULL,
            UNIQUE(id_linea,sistema,tipo,referencia),
            FOREIGN KEY(id_comunidad,id_linea) REFERENCES erp_regularizacion_lineas(id_comunidad,id_linea)
        )""",
        """CREATE TABLE erp_ajustes_plan (
            id_ajuste INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_plan INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            concepto_clave TEXT NOT NULL,
            importe_centimos INTEGER NOT NULL,
            motivo TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            estado TEXT NOT NULL CHECK(estado IN ('borrador','aprobado','emitido','cancelado')),
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_ajuste),
            FOREIGN KEY(id_comunidad,id_plan) REFERENCES erp_planes_cuota(id_comunidad,id_plan),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_personas_cobro (
            id_persona_cobro INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            tipo TEXT NOT NULL CHECK(tipo IN ('fisica','juridica','desconocida')),
            nombre TEXT NOT NULL,
            identificacion TEXT,
            direccion TEXT,
            idioma TEXT,
            estado TEXT NOT NULL DEFAULT 'activa' CHECK(estado IN ('activa','inactiva')),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_persona_cobro),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_persona_cobro_contactos (
            id_contacto INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_persona_cobro INTEGER NOT NULL,
            tipo TEXT NOT NULL,
            valor TEXT NOT NULL,
            valor_normalizado TEXT NOT NULL,
            principal INTEGER NOT NULL DEFAULT 0 CHECK(principal IN (0,1)),
            verificado INTEGER NOT NULL DEFAULT 0 CHECK(verificado IN (0,1)),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            activo INTEGER NOT NULL DEFAULT 1 CHECK(activo IN (0,1)),
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            creado_en TEXT NOT NULL,
            creado_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_contacto),
            FOREIGN KEY(id_comunidad,id_persona_cobro) REFERENCES erp_personas_cobro(id_comunidad,id_persona_cobro),
            FOREIGN KEY(creado_por) REFERENCES usuarios(id_usuario),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta>efectiva_desde)
        )""",
        """CREATE UNIQUE INDEX ux_erp_persona_cobro_contacto_principal ON erp_persona_cobro_contactos(id_persona_cobro,tipo) WHERE principal=1 AND activo=1""",
        """CREATE TABLE erp_ocupaciones (
            id_ocupacion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            tipo TEXT NOT NULL DEFAULT 'arrendamiento',
            version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            origen TEXT NOT NULL,
            UNIQUE(id_comunidad,id_ocupacion),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_ocupacion_versiones (
            id_ocupacion_version INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_ocupacion INTEGER NOT NULL,
            version INTEGER NOT NULL CHECK(version>0),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            estado TEXT NOT NULL CHECK(estado IN ('borrador','confirmada','sustituida','anulada')),
            origen TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            id_version_sustituida INTEGER,
            UNIQUE(id_ocupacion,version),
            UNIQUE(id_comunidad,id_ocupacion_version),
            FOREIGN KEY(id_comunidad,id_ocupacion) REFERENCES erp_ocupaciones(id_comunidad,id_ocupacion),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(id_version_sustituida) REFERENCES erp_ocupacion_versiones(id_ocupacion_version),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta>efectiva_desde)
        )""",
        """CREATE TABLE erp_ocupacion_personas (
            id_ocupacion_persona INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_ocupacion_version INTEGER NOT NULL,
            id_propietario INTEGER,
            id_persona_cobro INTEGER,
            papel TEXT NOT NULL DEFAULT 'inquilino',
            UNIQUE(id_ocupacion_version,id_propietario,id_persona_cobro,papel),
            FOREIGN KEY(id_comunidad,id_ocupacion_version) REFERENCES erp_ocupacion_versiones(id_comunidad,id_ocupacion_version),
            FOREIGN KEY(id_comunidad,id_propietario) REFERENCES cf_propietarios(id_comunidad,id_propietario),
            FOREIGN KEY(id_comunidad,id_persona_cobro) REFERENCES erp_personas_cobro(id_comunidad,id_persona_cobro),
            CHECK((id_propietario IS NOT NULL)!=(id_persona_cobro IS NOT NULL))
        )""",
        """CREATE TABLE erp_config_recibo_versiones (
            id_config_recibo INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            alcance TEXT NOT NULL DEFAULT 'ordinario',
            concepto_clave TEXT,
            version INTEGER NOT NULL CHECK(version>0),
            efectiva_desde TEXT,
            efectiva_hasta TEXT,
            registrada_en TEXT NOT NULL,
            registrada_por INTEGER NOT NULL,
            estado TEXT NOT NULL CHECK(estado IN ('borrador','confirmada','sustituida','anulada')),
            destinatario_propietario_id INTEGER,
            destinatario_persona_cobro_id INTEGER,
            pagador_propietario_id INTEGER,
            pagador_persona_cobro_id INTEGER,
            medio_previsto TEXT NOT NULL CHECK(medio_previsto IN ('transferencia','domiciliacion_pendiente','otro')),
            referencia_medio TEXT,
            origen TEXT NOT NULL,
            evidencia_tipo TEXT,
            evidencia_id TEXT,
            id_version_sustituida INTEGER,
            UNIQUE(id_propiedad,alcance,concepto_clave,version),
            UNIQUE(id_comunidad,id_config_recibo),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(id_comunidad,destinatario_propietario_id) REFERENCES cf_propietarios(id_comunidad,id_propietario),
            FOREIGN KEY(id_comunidad,destinatario_persona_cobro_id) REFERENCES erp_personas_cobro(id_comunidad,id_persona_cobro),
            FOREIGN KEY(id_comunidad,pagador_propietario_id) REFERENCES cf_propietarios(id_comunidad,id_propietario),
            FOREIGN KEY(id_comunidad,pagador_persona_cobro_id) REFERENCES erp_personas_cobro(id_comunidad,id_persona_cobro),
            FOREIGN KEY(registrada_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(id_version_sustituida) REFERENCES erp_config_recibo_versiones(id_config_recibo),
            CHECK((destinatario_propietario_id IS NOT NULL)!=(destinatario_persona_cobro_id IS NOT NULL)),
            CHECK((pagador_propietario_id IS NOT NULL)!=(pagador_persona_cobro_id IS NOT NULL)),
            CHECK(efectiva_hasta IS NULL OR efectiva_desde IS NULL OR efectiva_hasta>efectiva_desde)
        )""",
        """CREATE TABLE erp_plan_destinatarios_snapshot (
            id_snapshot INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_plan_version INTEGER NOT NULL,
            id_periodo_plan INTEGER NOT NULL,
            id_propiedad INTEGER NOT NULL,
            fecha_emision_referencia TEXT NOT NULL,
            conocida_en TEXT NOT NULL,
            id_config_recibo INTEGER,
            titulares_json TEXT NOT NULL,
            destinatario_json TEXT,
            pagador_json TEXT,
            estado TEXT NOT NULL CHECK(estado IN ('previsto','pendiente_revision','confirmado')),
            UNIQUE(id_plan_version,id_periodo_plan,id_propiedad),
            FOREIGN KEY(id_comunidad,id_plan_version) REFERENCES erp_plan_versiones(id_comunidad,id_plan_version),
            FOREIGN KEY(id_comunidad,id_periodo_plan) REFERENCES erp_plan_periodos(id_comunidad,id_periodo_plan),
            FOREIGN KEY(id_comunidad,id_propiedad) REFERENCES cf_propiedades(id_comunidad,id_propiedad),
            FOREIGN KEY(id_comunidad,id_config_recibo) REFERENCES erp_config_recibo_versiones(id_comunidad,id_config_recibo)
        )""",
        """CREATE TABLE erp_importaciones_presupuesto (
            id_importacion INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            hash_archivo TEXT NOT NULL,
            nombre_archivo TEXT NOT NULL,
            ruta_privada TEXT,
            formato TEXT NOT NULL,
            estado TEXT NOT NULL CHECK(estado IN ('staging','revisada','confirmada','cancelada')),
            id_presupuesto INTEGER,
            parametros_json TEXT NOT NULL DEFAULT '{}',
            creada_en TEXT NOT NULL,
            creada_por INTEGER NOT NULL,
            confirmada_en TEXT,
            confirmada_por INTEGER,
            UNIQUE(id_comunidad,hash_archivo),
            UNIQUE(id_comunidad,id_importacion),
            FOREIGN KEY(id_comunidad) REFERENCES comunidades(id_comunidad),
            FOREIGN KEY(id_comunidad,id_presupuesto) REFERENCES erp_presupuestos(id_comunidad,id_presupuesto),
            FOREIGN KEY(creada_por) REFERENCES usuarios(id_usuario),
            FOREIGN KEY(confirmada_por) REFERENCES usuarios(id_usuario)
        )""",
        """CREATE TABLE erp_importacion_presupuesto_filas (
            id_fila INTEGER PRIMARY KEY AUTOINCREMENT,
            id_comunidad INTEGER NOT NULL,
            id_importacion INTEGER NOT NULL,
            hoja TEXT,
            fila TEXT NOT NULL,
            capitulo_original TEXT,
            concepto_original TEXT,
            importe_original TEXT,
            importe_centimos INTEGER,
            id_capitulo_destino INTEGER,
            id_partida_destino INTEGER,
            decision TEXT NOT NULL CHECK(decision IN ('pendiente','crear','vincular','excluir')),
            incidencia TEXT,
            UNIQUE(id_importacion,hoja,fila),
            FOREIGN KEY(id_comunidad,id_importacion) REFERENCES erp_importaciones_presupuesto(id_comunidad,id_importacion)
        )""",
        "CREATE INDEX idx_erp_presupuesto_estado ON erp_presupuestos(id_comunidad,id_ejercicio,estado)",
        "CREATE INDEX idx_erp_presupuesto_version ON erp_presupuesto_versiones(id_comunidad,id_presupuesto,estado)",
        "CREATE INDEX idx_erp_partida_version ON erp_presupuesto_partidas(id_comunidad,id_presupuesto_version,id_capitulo)",
        "CREATE INDEX idx_erp_simulacion_origen ON erp_simulaciones(id_comunidad,origen_tipo,origen_id,estado)",
        "CREATE INDEX idx_erp_calculo_propiedad ON erp_calculo_lineas(id_comunidad,id_propiedad,id_simulacion)",
        "CREATE INDEX idx_erp_config_recibo_temporal ON erp_config_recibo_versiones(id_comunidad,id_propiedad,efectiva_desde,efectiva_hasta,registrada_en)",
        "CREATE INDEX idx_erp_ocupacion_propiedad ON erp_ocupaciones(id_comunidad,id_propiedad)",
        "CREATE INDEX idx_erp_importacion_presupuesto_estado ON erp_importaciones_presupuesto(id_comunidad,estado,creada_en)",
        "CREATE UNIQUE INDEX ux_erp_importacion_presupuesto_fila ON erp_importacion_presupuesto_filas(id_importacion,COALESCE(hoja,''),fila)",
        "CREATE INDEX idx_erp_presupuesto_permisos_comunidad ON erp_presupuesto_permisos(id_comunidad,id_usuario,activo)",
    )),
)


def _bootstrap(conn):
    conn.execute("""CREATE TABLE IF NOT EXISTS erp_schema_migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        checksum TEXT NOT NULL,
        applied_at_utc TEXT NOT NULL
    )""")


def apply_all(conn, migrations=MIGRATIONS):
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA busy_timeout=30000")
    _bootstrap(conn)
    applied = {int(row[0]): (row[1], row[2]) for row in conn.execute(
        "SELECT version,name,checksum FROM erp_schema_migrations"
    )}
    last = 0
    for migration in migrations:
        if migration.version <= last:
            raise RuntimeError("Las migraciones ERP no tienen un orden creciente unico.")
        last = migration.version
        previous = applied.get(migration.version)
        if previous:
            if previous != (migration.name, migration.checksum):
                raise RuntimeError(f"La migracion ERP {migration.version} no coincide con la aplicada.")
            continue
        if migration.foreign_keys_off:
            conn.execute("PRAGMA foreign_keys=OFF")
        conn.execute("BEGIN IMMEDIATE")
        try:
            for statement in migration.statements:
                conn.execute(statement)
            if migration.foreign_keys_off:
                violations = list(conn.execute("PRAGMA foreign_key_check"))
                if violations:
                    raise RuntimeError(
                        f"La migracion ERP {migration.version} deja {len(violations)} relaciones invalidas."
                    )
            conn.execute(
                "INSERT INTO erp_schema_migrations(version,name,checksum,applied_at_utc) VALUES (?,?,?,?)",
                (migration.version, migration.name, migration.checksum, utc_now()),
            )
        except Exception:
            conn.rollback()
            raise
        else:
            conn.commit()
        finally:
            if migration.foreign_keys_off:
                conn.execute("PRAGMA foreign_keys=ON")
    return {"schema_version": max(applied.keys() | {m.version for m in migrations}, default=0)}
