// ERP 5 uses the protected bank transport and the existing financial design system.
function createReconciliationUI(ctx) {
  const {api,html:h,root}=ctx;
  const money=value=>value===null||value===undefined?'No verificable':ctx.moneyLabel(value);
  const signedMoneyCents=value=>{const v=String(value).trim();return (v.startsWith('-')?'-':'')+ctx.moneyCents(v.startsWith('-')?v.slice(1):v);};
  let s,epoch=0;
  const today=()=>new Date().toLocaleDateString('sv-SE');
  const names={read:'Consultar',import:'Importar extractos',propose:'Preparar propuestas',confirm:'Confirmar conciliacion',
    manage_outflows:'Pagos y comisiones',manage_transfers:'Transferencias',correct:'Corregir',close:'Cerrar conciliacion',
    reopen:'Reabrir',configure:'Configurar cobertura',export:'Exportar informes',audit:'Auditoria'};
  const states={pendiente:'Pendiente de identificar',parcial:'Parcialmente conciliado',conciliado:'Conciliado',rectificado:'Rectificado',
    cerrado:'Cerrado',cerrado_pendientes:'Cerrado con pendientes',reabierto:'Reabierto',en_transito:'En transito',confirmada:'Confirmada'};
  const actions={link_collection:'Enlazar cobro existente',record_collection:'Registrar cobro',link_return:'Enlazar devolucion',
    link_refund:'Enlazar reintegro',link_outflow:'Enlazar pago/comision',record_outflow:'Registrar pago/comision',
    return:'Registrar devolucion',refund:'Reintegrar saldo a favor'};
  const factNames={collection:'Cobro',return:'Devolucion',refund:'Reintegro',outflow:'Salida',transfer:'Transferencia'};
  const button=(a,label,extra='',cls='')=>`<button type="button" data-reconcile="${a}" class="${cls}" ${extra}>${h(label)}</button>`;
  const input=(n,label,type='text',value='',required=true)=>`<label>${h(label)}<input name="${n}" type="${type}" value="${h(value??'')}" ${required?'required':''}></label>`;
  const select=(n,label,opts,value='')=>`<label>${h(label)}<select name="${n}">${opts.map(([v,t])=>`<option value="${h(v)}" ${String(v)===String(value)?'selected':''}>${h(t)}</option>`).join('')}</select></label>`;
  const table=(headers,rows)=>`<div class="finTableWrap"><table class="masterDataTable finTable"><thead><tr>${headers.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td data-label="${h(headers[i])}">${v}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}">No hay registros.</td></tr>`}</tbody></table></div>`;
  const can=k=>Boolean(s.permissions?.[k]);
  async function post(action,body){const current=epoch;const result=await api('/api/erp/banking/'+action,{method:'POST',body:JSON.stringify({...body,id_comunidad:s.community})});if(current!==epoch)throw new Error('Ha cambiado la comunidad.');return result;}
  async function q(name,filters={}){return (await post('query',{query:'erp5.'+name,filters})).entity;}
  async function qb(name,filters={}){return (await post('query',{query:'erp4.'+name,filters})).entity;}
  async function command(name,payload,version,key){return (await post('command',{command:'erp5.'+name,payload,expected_version:version,
    idempotency_key:key||crypto.randomUUID(),reason:s.reason||'Operacion bancaria revisada por el usuario',evidence:{type:'external_reference',id:s.evidence||'revision-erp5-'+s.community}})).entity;}
  const accountOptions=()=>s.accounts.map(a=>[a.id,a.label]);
  const filters=()=>({treasury_id:s.account,start_on:s.start,end_on:s.end});
  const proposalComponent=(id,p)=>({movement_id:id,action:p.action,amount_cents:p.amount_cents,
    ...(p.fact_id?{fact_id:p.fact_id}:{}),...(p.allocations?{allocations:p.allocations}:{})});
  async function load(){const snapshot=s;s.loading=true;render();try{
    const workspace=await q('workspace.get');s.accounts=workspace.accounts;s.permissions=workspace.permissions;s.userId=workspace.current_user_id;s.account=s.account||s.accounts.find(a=>a.kind==='banco')?.id;
    if(s.account){s.list=await q('movement.list',{...filters(),...s.context,state:s.state||undefined,search:s.search||undefined,offset:s.offset,limit:50});s.balances=await q('balances.get',filters());s.closures=await q('closure.list',{treasury_id:s.account});}
  }catch(e){if(s!==snapshot)return;s.error=e.message;if(e.status===403&&ctx.isSuperuser?.()){try{s.permissionData=await q('permissions.get');s.form={type:'permissions'};}catch{}}}finally{if(s===snapshot){s.loading=false;render();}}}
  function toolbar(){return `<div class="budgetToolbar">${button('remittances','Remesas')}${select('community','Comunidad',ctx.communities().map(c=>[c.id_comunidad,c.nombre]),s.community)}${select('account','Cuenta',accountOptions(),s.account)}${input('start','Desde','date',s.start)}${input('end','Hasta','date',s.end)}${button('reload','Actualizar')}</div>`;}
  function render(){if(!s||!ctx.active())return;root().setAttribute?.('aria-busy',String(Boolean(s.loading||s.busy)));root().innerHTML=`<div class="finWorkspace bankWorkspace reconcileWorkspace">${toolbar()}<h2>Conciliacion bancaria</h2>
    ${s.scope?`<p>${h(s.scope)} · Correspondencias del expediente. Saldos de la cuenta completa.</p>`:''}${s.error?`<div class="finWarning" role="alert">${h(s.error)}</div>`:''}${s.message?`<p role="status">${h(s.message)}</p>`:''}
    ${s.loading?'<p role="status">Cargando...</p>':s.review?reviewHtml():s.form?formHtml():s.detail?detailHtml():listHtml()}</div>`;bind();}
  function listHtml(){const b=s.balances;const closed=s.closures?.items.find(c=>c.start_on===s.start&&c.end_on===s.end&&c.state!=='reabierto');return `${closed?`<p role="status">${h(states[closed.state])}. Reabrir antes de modificar este periodo.</p>`:''}${b?`<div class="finSummary">${table(['Saldo comunicado','Saldo reconstruido','Diferencia','Cobertura'],[[money(b.reported_cents),money(b.calculated_cents),money(b.difference_cents),b.complete?'Completa':'Sin acreditar']])}</div>`:''}
    <div class="toolbar">${can('import')?button('import','Importar extracto','','green')+button('manual','Apunte manual'):''}${can('close')?button('close','Cerrar conciliacion'):''}${can('export')?select('report_format','Informe',[['xlsx','Excel'],['csv','CSV'],['pdf','PDF']])+button('export','Descargar'):''}</div>
    <details><summary>Configuracion del periodo</summary><div class="toolbar">${can('configure')?button('opening','Acreditar saldos')+button('source','Activar origen del periodo'):''}${ctx.isSuperuser?.()?button('permissions','Permisos'):''}</div></details>
    <div class="budgetToolbar">${select('state','Estado',[['','Todos'],['pendiente','Pendientes'],['parcial','Parciales'],['conciliado','Conciliados']],s.state)}${input('search','Buscar','search',s.search,false)}${button('filter','Filtrar')}
      ${button('select-all','Seleccionar visibles')}${button('clear-selection','Deseleccionar')}<span data-selected-count>${s.selected.size} seleccionados · maximo 200 por lote</span>${can('propose')?button('bulk','Revisar seleccion'):''}</div>
    ${table(['','Fecha operacion','Concepto','Importe','Estado',''],(s.list?.items||[]).map(r=>[
      `<input type="checkbox" data-movement-select="${r.id}" aria-label="Seleccionar movimiento" ${s.selected.has(r.id)?'checked':''}>`,h(r.operation_on),h(r.concept),money(r.amount_cents),h(states[r.state]||r.state),button('detail','Revisar',`data-id="${r.id}"`)]))}
    <div class="toolbar">${button('prev','Anterior',s.offset?'':'disabled')}<span>${s.list?.total||0} movimientos</span>${button('next','Siguiente',s.offset+50<(s.list?.total||0)?'':'disabled')}</div>
    <details><summary>Cierres anteriores</summary>${table(['Periodo','Estado',''],(s.closures?.items||[]).map(c=>[h(c.start_on+' - '+c.end_on),h(states[c.state]),can('reopen')&&c.state!=='reabierto'?button('reopen','Reabrir',`data-id="${c.id}" data-version="${c.version}"`):'']))}</details>`;}
  function detailHtml(){const r=s.detail;return `<div class="toolbar">${button('back','Volver')}</div><h3>${h(r.concept)}</h3>
    ${table(['Operacion','Valor','Importe','Pendiente'],[[h(r.operation_on),h(r.value_on||'No consta'),money(r.amount_cents),money(r.remaining_cents)]])}
    <div class="toolbar">${can('propose')?button('component','Asignar / dividir')+button('bank-result','Enlazar resultado de remesa'):''}${can('manage_transfers')?button('transfer','Transferencia interna')+button('complete-transfer','Completar transferencia'):''}${button('pending','Documentar pendiente')}${can('correct')?button('correction','Rectificar apunte'):''}</div>
    ${can('propose')?`<div class="budgetToolbar">${input('window_days','Buscar a +/- dias','number',s.proposals?.window_days??7)}${button('proposals','Buscar coincidencias')}</div>`:''}
    ${s.proposals?.truncated?'<div class="finWarning">Hay mas candidatos. No se presupone una coincidencia unica.</div>':''}
    ${table(['Propuesta','Importe','Confianza',''],(s.proposals?.items||[]).map((p,i)=>[h(p.reason),money(p.amount_cents),h(p.confidence),button('candidate','Revisar',`data-index="${i}"`)]))}
    <h3>Historico de correspondencias</h3>${table(['Operacion','Tipo','Importe','Estado',''],(r.history||[]).map(c=>[h(String(c.match_id)),h(factNames[c.kind]||c.kind),money(c.amount_cents),h(c.reverses_id?'Compensacion':c.reversed?'Enlace revertido':c.document_pending?'Pendiente de documento':'Confirmado'),
      can('correct')&&!c.reverses_id?(c.kind==='transfer'&&!c.fact_rectified?button('fact-reversal','Rectificar transferencia',`data-kind="transfer" data-id="${c.transfer_id}"`):(!c.reversed?button('reverse','Desconciliar',`data-id="${c.match_id}"`):'')+(c.kind==='outflow'&&!c.fact_rectified?button('fact-reversal','Rectificar salida',`data-kind="outflow" data-id="${c.outflow_id}"`):'')):'']))}
    <details><summary>Evidencias originales</summary>${(r.imports||[]).map(i=>button('original','Descargar extracto',`data-id="${i.import_id}"`)).join('')}</details>`;}
  function evidenceFields(){return `<details><summary>Motivo y documento</summary>${input('reason','Motivo','text',s.reason,false)}${input('evidence','Referencia del justificante','text',s.evidence,false)}</details>`;}
  function formHtml(){const f=s.form;let fields='';
    if(f.type==='import')fields=`<label>Extracto<input name="file" type="file" accept=".csv,.xls,.xlsx,.txt,.xml" required></label>${select('profile','Formato',[['tabular-v1','Excel / CSV'],['cuaderno43-v1','Cuaderno 43'],['camt.053.001.08','Extracto ISO 20022'],['camt.054.001.08','Notificacion ISO 20022']])}`;
    if(f.type==='block')fields=select('block_index','Bloque de cuenta',[['','Selecciona el bloque'],...s.blockData.blocks.map(b=>[b.index,b.label])]);
    if(f.type==='manual')fields=input('on','Fecha operacion','date',today())+input('value_on','Fecha valor','date','',false)+input('amount','Importe con signo','text','')+input('concept','Concepto')+input('reference','Referencia','text','',false);
    if(f.type==='mapping'){const opts=[['','No utilizar'],...s.mappingData.headers.map((x,i)=>[i,x])];fields=select('saved_profile','Mapeo guardado',[['','Seleccionar manualmente'],...(s.mappingData.saved_profiles||[]).map(p=>[p.id,p.name])])+Object.entries({operation_on:'Fecha operacion',value_on:'Fecha valor',amount:'Importe con signo',debit:'Cargos',credit:'Abonos',concept:'Concepto',counterparty:'Ordenante / beneficiario',reference:'Referencia',external_id:'Identificador unico del apunte',balance:'Saldo'}).map(([k,v])=>select(k,v,opts)).join('')+select('decimal','Separador decimal',[['.', 'Punto'],[',','Coma']])+select('date_format','Formato de fecha',[['iso','AAAA-MM-DD'],['dmy','DD/MM/AAAA'],['mdy','MM/DD/AAAA']])+`<details><summary>Reutilizar este mapeo</summary><label><input name="save_mapping" type="checkbox">Guardar despues de confirmar</label>${input('profile_name','Nombre del mapeo','text','',false)}</details>`;}
    if(f.type==='component')fields=`${select('action','Que corresponde',Object.entries(actions),f.action||'record_collection')}${input('amount','Importe a asignar','text',moneyInput(f.amount||s.detail.remaining_cents))}
      <div data-fact-field>${select('fact','Hecho existente',[['','Selecciona'],...(s.facts?.items||[]).map(x=>[x.kind+':'+x.id,(x.kind==='collection'?'Cobro':x.kind==='return'?'Devolucion':x.kind==='refund'?'Reintegro':'Pago')+' '+x.effective_on+' · '+money(x.amount_cents)])],f.fact||'')}</div>
      <div data-outflow-field>${select('kind','Tipo',[['payment','Pago proveedor'],['commission','Comision'],['other','Otro cargo']])}${input('description','Concepto de la salida','text',s.detail.concept)}${input('document','Documento vinculado','text','',false)}</div>
      <details data-allocation-field><summary>Aplicar cobro a recibos</summary>${(s.facts?.receipts||[]).map(r=>{const a=f.allocations?.find(a=>a.receipt_id===r.id);return `<label><input type="checkbox" name="receipt" value="${r.id}" ${a?'checked':''}> ${h(r.number+' · '+r.description)} (${money(r.pending_cents)})<input name="allocation-${r.id}" aria-label="Importe a aplicar" value="${h(moneyInput(a?.amount_cents||r.pending_cents))}"></label>`;}).join('')}</details>
      <div data-return-field>${select('collection','Cobro de origen',[['','Selecciona'],...(s.facts?.collections||[]).map(c=>[c.id,c.effective_on+' · '+money(c.amount_cents)])])}${input('free','Importe libre devuelto','text','0,00')}<div data-reversals></div></div>
      <div data-refund-field>${select('refund_collection','Saldo a favor de origen',[['','Selecciona'],...(s.facts?.collections||[]).filter(c=>c.beneficiary&&BigInt(c.available_cents)>0n).map(c=>[c.id,c.effective_on+' · disponible '+money(c.available_cents)])])}</div>
      ${s.facts?.truncated?'<div class="finWarning">Lista limitada a 200 registros. No se supone que incluya todos los resultados.</div>':''}`;
    if(f.type==='component')fields+=`<details><summary>Desglose bruto / neto</summary>${input('net_evidence','Referencia del desglose acreditado','text',s.netEvidence,false)}</details>${s.components.length?table(['Importe preparado','Accion',''],s.components.map((c,i)=>[money(c.amount_cents),h(actions[c.action]||c.action),button('remove-component','Quitar',`data-index="${i}"`)]))+button('review-components','Revisar desglose'):''}${button('stage-component','Anadir al desglose')}`;
    if(f.type==='pending')fields=input('note','Motivo del pendiente')+input('review_on','Revisar el','date',today());
    if(f.type==='opening')fields=input('opening','Saldo inicial','text','0,00')+input('closing','Saldo final comunicado','text','0,00')+`<label class="finCheck"><input name="complete" type="checkbox">Cobertura completa acreditada</label>`;
    if(f.type==='transfer')fields=select('destination','Otra cuenta',[['','Selecciona'],...accountOptions().filter(([id])=>id!==s.account)])+input('amount','Principal','text',moneyInput(s.detail.remaining_cents).replace('-',''))+select('counter_movement','Otro extremo',[['','Todavia no consta']])+input('cash_evidence','Justificante de caja (si corresponde)','text','',false);
    if(f.type==='permissions')fields=select('user','Usuario',s.permissionData.users.map(u=>[u.id_usuario,u.nombre]))+select('capability','Permiso',s.permissionData.capabilities.map(c=>[c,names[c]]))+select('allowed','Acceso',[['true','Permitir'],['false','Denegar']]);
    if(f.type==='complete-transfer')fields=select('transfer','Transferencia en transito',[['','Selecciona'],...(s.transfers?.items||[]).filter(t=>t.state==='en_transito'&&(t.source_id===s.account||t.destination_id===s.account)).map(t=>[t.id,'Pendiente '+money(t.in_transit_cents)+' · '+(t.source_id===s.account?'Salida':'Entrada')])])+input('amount','Principal a acreditar','text',moneyInput(s.detail.remaining_cents).replace('-',''));
    if(f.type==='correction')fields=select('kind','Correccion',[['duplicate','Es un duplicado'],['substitute','Sustituir por apunte corregido']])+select('replacement','Apunte que se conserva',[['','Selecciona'],...(s.replacements||[]).filter(r=>r.id!==s.detail.id).map(r=>[r.id,r.operation_on+' · '+r.concept+' · '+money(r.amount_cents)])]);
    if(f.type==='original')fields=input('password','Confirma tu contrasena','password')+input('reason','Motivo del acceso');
    if(f.type==='fact-reversal')fields=input('effective_on','Fecha de rectificacion','date',today());
    if(f.type==='identity')fields=input('identity_search','Buscar apunte existente','search',s.identitySearch||'',false)+button('identity-search','Buscar')+select('existing_movement','Apunte acreditado',[['','Selecciona'],...(s.identityCandidates?.items||[]).filter(x=>x.state!=='rectificado').map(x=>[x.id,x.operation_on+' · '+x.concept+' · '+money(x.amount_cents)])])+input('identity_reason','Evidencia de que es el mismo apunte');
    if(f.type==='bank-result')fields=select('result','Resultado bancario',[['','Selecciona'],...(s.results?.items||[]).filter(r=>r.state!=='confirmado').map(r=>[r.id,'Resultado '+r.registered_at.slice(0,10)])])+`<div data-result-lines></div>`;
    return `<div class="toolbar">${button('back','Volver')}</div><form data-reconciliation-form><h3>${h({import:'Importar extracto',block:'Seleccionar cuenta del archivo',manual:'Apunte manual observado',mapping:'Mapear columnas',component:'Asignar importe',pending:'Documentar pendiente',opening:'Saldos acreditados',transfer:'Transferencia interna','complete-transfer':'Completar transferencia',correction:'Rectificar apunte',original:'Descargar evidencia protegida','bank-result':'Enlazar resultado de remesa','fact-reversal':'Rectificar hecho de tesoreria',identity:'Enlazar evidencia del mismo apunte',permissions:'Permisos'}[f.type])}</h3>${f.type==='identity'&&s.identityCandidates?.total>200?'<div class="finWarning">Se muestran los primeros 200 resultados. Concreta la busqueda para localizar el apunte.</div>':''}<div class="masterDataFormGrid">${fields}</div>${f.type==='original'?'':evidenceFields()}<button class="green" type="submit">Revisar</button></form>`;}
  const moneyInput=value=>{const v=BigInt(value||'0');const a=v<0n?-v:v;return (v<0n?'-':'')+(a/100n).toString()+','+(a%100n).toString().padStart(2,'0');};
  function reviewHtml(){const r=s.review;const content=r.type==='statement'?table(['Fila','Concepto','Importe','Decision'],r.data.rows.map(x=>[h(String(x.row)),h(x.concept),money(x.amount_cents),r.decisions?.[x.row]?.action==='alias'?h('Evidencia del apunte seleccionado')+button('identity','Cambiar enlace',`data-row="${x.row}"`):(x.action==='review'?select('decision-'+x.row,'Coincidencia',[['','Revisar'],['new','Es otro movimiento'],...x.candidates.map(id=>['link:'+id,'Enlazar movimiento '+id])]):h(x.action))+(r.data.state!=='confirmada'&&['new','review'].includes(x.action)?button('identity','Enlazar otro apunte acreditado',`data-row="${x.row}"`):'')])):
      r.type==='match'?table(['Accion','Importe','Movimiento','Aplicacion a recibos'],r.data.components.map(x=>[h(actions[x.action]||x.action),money(x.amount_cents),h(String(x.movement_id)),Array.isArray(x.economic_snapshot)?x.economic_snapshot.map(a=>h(a.number+' · '+a.description)+' · '+money(a.allocated_cents)).join('<br>'):'Sin nueva aplicacion']))+table(['Movimiento','Pendiente despues de confirmar'],(r.data.remaining||[]).map(x=>[h(String(x.movement_id)),money(x.after_cents)])):
      ['closure','source'].includes(r.type)?table(['Saldo comunicado','Saldo reconstruido','Pendientes'],[[money(r.data.reported_cents),money(r.data.calculated_cents),h(String(r.data.pending?.length||0))]]):r.type==='fact_reversal'?table(['Fecha','Compensacion','Cuenta'],r.data.entries.map(x=>[h(x.effective_on),money(x.amount_cents),h(s.accounts.find(a=>a.id===x.treasury_id)?.label||'Cuenta')])):r.type==='correction'?table(['Correccion','Movimiento conservado'],[[h(r.payload.kind),h(String(r.payload.replacement_id))]]):table(['Estado','En transito'],[[h(states[r.data.state]||r.data.state),money(r.data.in_transit_cents)]]);
    return `<div class="toolbar">${button('back','Volver')}</div><h3>Revisar antes de confirmar</h3>${content}${r.data.errors?.length?`<div class="finWarning">${r.data.errors.map(x=>h('Fila '+x.row+': '+x.error)).join('<br>')}</div><label><input name="exclude_errors" type="checkbox">Excluir expresamente estas filas; cobertura incompleta</label>`:''}<div class="toolbar">${button('confirm','Confirmar','','green')}${r.type==='statement'&&s.file?.profile==='tabular-v1'&&r.data.state!=='confirmada'?button('remap','Corregir columnas'):''}${r.type==='match'?button('add-component','Anadir otro importe'):''}</div>`;}
  async function open(community,context={},scope=''){epoch++;const {start_on,end_on,treasury_id,...filters}=context;s={community,context:filters,scope,account:treasury_id||0,accounts:[],permissions:{},start:start_on||today().slice(0,7)+'-01',end:end_on||today(),offset:0,selected:new Set(),components:[],reason:'',evidence:''};return load();}
  async function showComponent(prefill={}){s.facts=await q('facts.list',{treasury_id:s.account});s.form={type:'component',...prefill};s.review=null;render();}
  async function act(a,b){s.error='';
    if(a==='remittances')return ctx.openRemittances(s.community);
    if(a==='reload'||a==='filter'){s.start=root().querySelector('[name=start]').value;s.end=root().querySelector('[name=end]').value;s.state=root().querySelector('[name=state]')?.value||'';s.search=root().querySelector('[name=search]')?.value||'';s.offset=0;return load();}
    if(a==='back'){if(s.form?.type==='identity'){s.form=null;s.review=s.identityReview;s.identityReview=null;return render();}s.form=null;s.review=null;s.detail=null;s.components=[];return load();}
    if(a==='import'||a==='opening'){s.form={type:a};return render();}
    if(a==='permissions'){s.permissionData=await q('permissions.get');s.form={type:a};return render();}
    if(a==='detail'){s.detail=await q('movement.get',{id:Number(b.dataset.id)});s.proposals=can('propose')?await q('proposals.get',{movement_id:s.detail.id}):{items:[]};s.components=[];s.netEvidence='';return render();}
    if(a==='stage-component')return submit(root().querySelector('[data-reconciliation-form]'),true);
    if(a==='remove-component'){s.components.splice(Number(b.dataset.index),1);return render();}
    if(a==='review-components'){const f=Object.fromEntries(new FormData(root().querySelector('[data-reconciliation-form]')));s.netEvidence=(f.net_evidence||'').trim();s.reason=f.reason||s.reason;s.evidence=f.evidence||s.evidence;
      s.review={type:'match',data:await command('match.preview',{components:s.components,...(s.netEvidence?{net_evidence:s.netEvidence}:{})})};s.form=null;return render();}
    if(a==='proposals'){const window=Number(root().querySelector('[name=window_days]').value);if(!Number.isInteger(window)||window<0||window>90)throw new Error('Indica entre 0 y 90 dias.');s.proposals=await q('proposals.get',{movement_id:s.detail.id,window_days:window});return render();}
    if(a==='component'||a==='add-component')return showComponent();
    if(a==='candidate'){const p=s.proposals.items[Number(b.dataset.index)];return showComponent({action:p.action,amount:p.amount_cents,fact:p.fact_id?p.action.replace('link_','')+':'+p.fact_id:'',allocations:p.allocations});}
    if(a==='manual'){s.form={type:a};return render();}
    if(a==='remap'){s.remap={id:s.review.data.id,version:s.review.data.version};s.review=null;s.form={type:'mapping'};return render();}
    if(a==='original'){s.form={type:a,id:Number(b.dataset.id)};return render();}
    if(a==='fact-reversal'){s.form={type:a,id:Number(b.dataset.id),kind:b.dataset.kind};return render();}
    if(a==='identity'){s.identityCandidates=await q('movement.list',{treasury_id:s.account,limit:200});s.identitySearch='';s.identityReview=s.review;s.review=null;s.form={type:a,row:Number(b.dataset.row)};return render();}
    if(a==='identity-search'){s.identitySearch=root().querySelector('[name=identity_search]').value;s.identityCandidates=await q('movement.list',{treasury_id:s.account,limit:200,search:s.identitySearch});return render();}
    if(a==='complete-transfer'){s.transfers=await q('transfer.list');s.form={type:a};return render();}
    if(a==='correction'){s.replacements=(await q('movement.list',{treasury_id:s.account,limit:200})).items;s.form={type:a};return render();}
    if(a==='bank-result'){s.results=await qb('results.list',{limit:200});s.facts=await q('facts.list',{treasury_id:s.account});s.form={type:a};return render();}
    if(a==='pending'||a==='transfer'){s.form={type:a};return render();}
    if(a==='reverse'){if(!confirm('Desconciliar el enlace conservando el cobro o pago original?'))return;await command('match.reverse',{id:Number(b.dataset.id)});s.detail=null;return load();}
    if(a==='reopen'){s.reason=prompt('Motivo de reapertura')||'';if(!s.reason)return;await command('closure.reopen',{id:Number(b.dataset.id)},Number(b.dataset.version));return load();}
    if(a==='close'){s.review={type:'closure',data:await command('closure.preview',filters())};return render();}
    if(a==='source'){s.review={type:'source',data:await command('source.preview',filters())};return render();}
    if(a==='confirm'){const r=s.review;let p={proposal_id:r.data.id};let name=r.type==='closure'?'closure.confirm':r.type==='transfer'?'transfer.confirm':'match.confirm';
      if(r.type==='statement'){name='statement.confirm';p={id:r.data.id,decisions:{...r.decisions},exclude_errors:Boolean(root().querySelector('[name=exclude_errors]')?.checked)};for(const x of r.data.rows){const v=root().querySelector(`[name="decision-${x.row}"]`)?.value;if(v==='new')p.decisions[x.row]={action:'new',reason:'El usuario confirma otra ocurrencia'};else if(v?.startsWith('link:'))p.decisions[x.row]={action:'link',id:Number(v.slice(5))};}}
      if(r.type==='source')name='source.confirm';if(r.type==='transfer_completion')name='transfer.complete_confirm';if(r.type==='fact_reversal')name='fact.reverse_confirm';if(r.type==='correction'){name='movement.correct';p=r.payload;}
      await command(name,p,r.data.version,r.key||(r.key=crypto.randomUUID()));const profile=r.type==='statement'?s.pendingProfile:null;s.pendingProfile=null;s.review=null;s.form=null;s.detail=null;s.components=[];s.message='Operacion confirmada.';
      if(profile){try{await command('profile.save',profile.payload,profile.version);s.message+=' Mapeo guardado.';}catch(e){s.message+=' El extracto esta confirmado, pero no se pudo guardar el mapeo: '+e.message;}}return load();}
    if(a==='prev'||a==='next'){s.offset+=a==='next'?50:-50;return load();}
    if(a==='select-all'){for(const r of s.list.items)s.selected.add(r.id);return render();}
    if(a==='clear-selection'){s.selected.clear();return render();}
    if(a==='bulk'){if(!s.selected.size||s.selected.size>200)throw new Error('Selecciona entre 1 y 200 movimientos por bloque.');s.components=[];for(const id of s.selected){const proposals=await q('proposals.get',{movement_id:id});if(proposals.truncated||proposals.items.length!==1)throw new Error('La seleccion incluye movimientos ambiguos. Revisalos individualmente.');s.components.push(proposalComponent(id,proposals.items[0]));}
      s.review={type:'match',data:await command('match.preview',{components:s.components})};return render();}
    if(a==='export'){const format=root().querySelector('[name=report_format]')?.value||'xlsx';const report=await command('report.export',{...filters(),format});const blob=new Blob([Uint8Array.from(atob(report.content_base64),c=>c.charCodeAt(0))],{type:{xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',csv:'text/csv;charset=utf-8',pdf:'application/pdf'}[format]});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=report.filename;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
  }
  async function submit(form,stageOnly=false){const f=Object.fromEntries(new FormData(form));s.reason=f.reason||s.reason;s.evidence=f.evidence||s.evidence;
    if(s.form.type==='identity'){if(!f.existing_movement||!f.identity_reason?.trim())throw new Error('Selecciona el apunte e indica su evidencia.');const r=s.identityReview;r.decisions={...r.decisions,[s.form.row]:{action:'alias',id:Number(f.existing_movement),reason:f.identity_reason}};s.identityReview=null;s.review=r;s.form=null;return render();}
    if(s.form.type==='fact-reversal'){if(!s.reason?.trim()||!s.evidence?.trim())throw new Error('Indica el motivo y la evidencia de la rectificacion.');s.review={type:'fact_reversal',data:await command('fact.reverse_preview',{kind:s.form.kind,id:s.form.id,effective_on:f.effective_on})};s.form=null;return render();}
    if(s.form.type==='manual'){s.review={type:'statement',data:await command('statement.preview',{treasury_id:s.account,profile:'manual-v1',rows:[{operation_on:f.on,...(f.value_on?{value_on:f.value_on}:{}),amount_cents:signedMoneyCents(f.amount),concept:f.concept,reference:f.reference||''}]})};s.form=null;return render();}
    if(s.form.type==='original'){await post('reauthenticate',{password:f.password});form.elements.password.value='';const response=await fetch('/api/erp/banking/statement-original',{method:'POST',cache:'no-store',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id_comunidad:s.community,import_id:s.form.id,reason:f.reason})});if(!response.ok)throw new Error((await response.json()).error||'Descarga no autorizada.');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1]||'extracto-original';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);s.form=null;return render();}
    if(s.form.type==='correction'){s.review={type:'correction',data:{version:s.detail.version},payload:{movement_id:s.detail.id,replacement_id:Number(f.replacement),kind:f.kind}};s.form=null;return render();}
    if(s.form.type==='complete-transfer'){const t=s.transfers.items.find(t=>t.id===Number(f.transfer));if(!t)throw new Error('Selecciona la transferencia.');s.review={type:'transfer_completion',data:await command('transfer.complete_preview',{transfer_id:t.id,legs:[{side:t.source_id===s.account?'source':'destination',movement_id:s.detail.id,amount_cents:ctx.moneyCents(f.amount)}]})};s.form=null;return render();}
    if(s.form.type==='import'){const file=form.querySelector('[name=file]').files[0];if(file.size>16*1024*1024)throw new Error('Maximo 16 MB.');const content=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});s.file={treasury_id:s.account,filename:file.name,content_base64:content,profile:f.profile};
      if(f.profile==='tabular-v1'){s.mappingData=await command('statement.analyze',s.file);s.form={type:'mapping'};return render();}s.blockData=await command('statement.analyze',s.file);if(s.blockData.requires_block){s.form={type:'block'};return render();}s.review={type:'statement',data:await command('statement.preview',s.file)};s.form=null;return render();}
    if(s.form.type==='block'){if(f.block_index==='')throw new Error('Selecciona el bloque de cuenta correspondiente.');s.file={...s.file,options:{block_index:Number(f.block_index)}};s.review={type:'statement',data:await command('statement.preview',s.file)};s.form=null;return render();}
    if(s.form.type==='mapping'){const mapping={};for(const k of ['operation_on','value_on','amount','debit','credit','concept','counterparty','reference','external_id','balance'])if(f[k]!=='')mapping[k]=Number(f[k]);const options={decimal_separator:f.decimal,date_format:f.date_format};s.pendingProfile=null;if(f.save_mapping){if(!f.profile_name?.trim())throw new Error('Indica el nombre del mapeo.');const existing=(await q('profile.list',{treasury_id:s.account})).items.filter(p=>p.kind==='mapping'&&p.name===f.profile_name.trim()).sort((a,b)=>b.version-a.version)[0];s.pendingProfile={payload:{treasury_id:s.account,name:f.profile_name.trim(),kind:'mapping',config:{mapping,options,header_signature:s.mappingData.header_signature}},version:existing?.version||0};}
      s.review={type:'statement',data:s.remap?await command('statement.remap',{id:s.remap.id,mapping,options},s.remap.version):await command('statement.preview',{...s.file,mapping,options})};s.remap=null;s.form=null;return render();}
    if(s.form.type==='component'){const action=f.action;const magnitude=signedMoneyCents(f.amount).replace('-','');const n=(['link_return','link_refund','link_outflow','record_outflow','return','refund'].includes(action)?'-':'')+magnitude;const c={movement_id:s.detail.id,action,amount_cents:n};if(action.startsWith('link_')){const [kind,id]=f.fact.split(':');if(action!=='link_'+kind)throw new Error('Selecciona un hecho del tipo correspondiente.');c.fact_id=Number(id);}if(action==='record_outflow'){c.kind=f.kind;c.description=f.description;if(f.document)c.document=f.document;}
      if(action==='record_collection'){c.allocations=[...form.querySelectorAll('[name=receipt]:checked')].map(x=>({receipt_id:Number(x.value),amount_cents:ctx.moneyCents(f['allocation-'+x.value])}));}
      if(action==='return'){c.return_payload={collection_id:Number(f.collection),effective_on:s.detail.operation_on,free_cents:ctx.moneyCents(f.free),reversals:[...form.querySelectorAll('[name=reversal]:checked')].map(x=>({allocation_id:Number(x.value),amount_cents:ctx.moneyCents(f['reversal-'+x.value])})),external_key:'erp5-return-'+crypto.randomUUID()};}
      if(action==='refund'){const collection=s.facts.collections.find(c=>c.id===Number(f.refund_collection));if(!collection?.beneficiary)throw new Error('Selecciona un saldo de titular acreditado.');c.refund_payload={collection_id:collection.id,beneficiary:collection.beneficiary,effective_on:s.detail.operation_on,amount_cents:(BigInt(n)<0n?-BigInt(n):BigInt(n)).toString()};}
      const netEvidence=(f.net_evidence||'').trim();const components=[...s.components,c];
      if(stageOnly){s.components=components;s.netEvidence=netEvidence;s.message='Importe anadido al desglose, todavia sin guardar.';return render();}
      s.review={type:'match',data:await command('match.preview',{components,...(netEvidence?{net_evidence:netEvidence}:{})})};s.components=components;s.netEvidence=netEvidence;s.form=null;return render();}
    if(s.form.type==='pending'){await command('pending.assign',{movement_id:s.detail.id,user_id:ctx.userId?.()||s.userId,review_on:f.review_on,note:f.note});s.form=null;s.detail=null;return load();}
    if(s.form.type==='opening'){await command('opening.confirm',{...filters(),opening_cents:signedMoneyCents(f.opening),closing_cents:signedMoneyCents(f.closing),balance_type:'booked',complete:Boolean(f.complete)});s.form=null;return load();}
    if(s.form.type==='transfer'){const negative=BigInt(s.detail.remaining_cents)<0n;const destination=Number(f.destination);const amount=ctx.moneyCents(f.amount).replace('-','');const other=s.accounts.find(a=>a.id===destination);const legs=[{side:negative?'source':'destination',movement_id:s.detail.id,amount_cents:amount}];if(f.counter_movement)legs.push({side:negative?'destination':'source',movement_id:Number(f.counter_movement),amount_cents:amount});else if(other?.kind==='caja'&&f.cash_evidence)legs.push({side:negative?'destination':'source',amount_cents:amount,effective_on:s.detail.operation_on,cash_evidence:f.cash_evidence});
      s.review={type:'transfer',data:await command('transfer.preview',{source_id:negative?s.account:destination,destination_id:negative?destination:s.account,amount_cents:amount,legs})};s.form=null;return render();}
    if(s.form.type==='permissions'){const user=Number(f.user);const previous=s.permissionData.items.find(x=>x.user_id===user&&x.capability===f.capability);await command('permissions.save',{user_id:user,capability:f.capability,allowed:f.allowed==='true'},previous?.version||0);s.form=null;return load();}
    if(s.form.type==='bank-result'){const decisions=[];for(const row of s.resultDetails.lines){if(!form.querySelector(`[name="result-row-${row.id}"]`)?.checked)continue;const action=f['result-action-'+row.id];const d={result_line_id:row.id,action};if(row.kind==='settlement'){d.allocate_cents=ctx.moneyCents(f['result-allocate-'+row.id]||'0');if(action==='link_collection')d.collection_id=Number(f['result-collection-'+row.id]);}else{d.collection_id=Number(f['result-collection-'+row.id]);if(action==='link_return')d.return_id=Number(f['result-return-'+row.id]);else d.return_spec={free_cents:ctx.moneyCents(f['result-free-'+row.id]||'0'),reversals:(s.resultChoices[row.id]?.collections||[]).flatMap(c=>c.allocations).filter(a=>BigInt(ctx.moneyCents(f['result-reverse-'+a.id]||'0'))>0n).map(a=>({allocation_id:a.id,amount_cents:ctx.moneyCents(f['result-reverse-'+a.id])}))};}decisions.push(d);}
      s.components.push({movement_id:s.detail.id,action:'bank_result',amount_cents:s.detail.remaining_cents,bank_result:{result_id:Number(f.result),decisions}});s.review={type:'match',data:await command('match.preview',{components:s.components})};s.form=null;return render();}
  }
  function bind(){root().querySelectorAll('[data-reconcile]').forEach(b=>b.onclick=()=>guard(()=>act(b.dataset.reconcile,b)));
    root().querySelectorAll('[data-movement-select]').forEach(c=>c.onchange=()=>{const id=Number(c.dataset.movementSelect);c.checked?s.selected.add(id):s.selected.delete(id);const counter=root().querySelector('[data-selected-count]');if(counter)counter.textContent=s.selected.size+' seleccionados · maximo 200 por lote';});
    root().querySelector('[name=community]')?.addEventListener('change',e=>open(Number(e.target.value)));
    root().querySelector('[name=account]')?.addEventListener('change',e=>{s.account=Number(e.target.value);s.selected.clear();s.form=null;s.review=null;s.detail=null;load();});
    const form=root().querySelector('[data-reconciliation-form]');if(form)form.onsubmit=e=>{e.preventDefault();guard(()=>submit(form));};
    const saved=root().querySelector('[name=saved_profile]');if(saved)saved.onchange=()=>{const p=s.mappingData.saved_profiles.find(p=>p.id===Number(saved.value));if(!p)return;for(const k of ['operation_on','value_on','amount','debit','credit','concept','counterparty','reference','external_id','balance'])form.elements[k].value=p.mapping[k]??'';form.elements.decimal.value=p.options.decimal_separator;form.elements.date_format.value=p.options.date_format;};
    const destination=root().querySelector('[name=destination]');if(destination)destination.onchange=()=>guard(async()=>{
      const items=await q('movement.list',{treasury_id:Number(destination.value),state:'pendiente',limit:200});
      const opposite=BigInt(s.detail.remaining_cents)<0n;
      root().querySelector('[name=counter_movement]').innerHTML='<option value="">Todavia no consta</option>'+items.items.filter(r=>(BigInt(r.remaining_cents)>0n)===opposite).map(r=>`<option value="${r.id}">${h(r.operation_on+' · '+r.concept+' · '+money(r.remaining_cents))}</option>`).join('');});
    const collection=root().querySelector('[name=collection]');if(collection)collection.onchange=()=>{const c=s.facts.collections.find(c=>c.id===Number(collection.value));root().querySelector('[data-reversals]').innerHTML=(c?.allocations||[]).map(a=>`<label><input name="reversal" type="checkbox" value="${a.id}">${h(a.number)}<input name="reversal-${a.id}" aria-label="Importe devuelto" value="${h(moneyInput(a.remaining_cents))}"></label>`).join('');};
    const result=root().querySelector('[name=result]');if(result)result.onchange=()=>guard(async()=>{s.resultDetails=await qb('results.get',{id:Number(result.value)});s.resultChoices={};for(const row of s.resultDetails.lines.filter(r=>r.matched&&r.state!=='confirmada'&&['settlement','returned'].includes(r.kind))){s.resultChoices[row.id]=await qb('results.choices',{result_line_id:row.id});}root().querySelector('[data-result-lines]').innerHTML=s.resultDetails.lines.filter(r=>s.resultChoices[r.id]).map(row=>{const choices=s.resultChoices[row.id].collections;return `<fieldset><legend><input type="checkbox" name="result-row-${row.id}"> ${h(row.kind==='settlement'?'Liquidacion':'Devolucion')} · ${money(row.amount_cents)}</legend>${select('result-action-'+row.id,'Accion',row.kind==='settlement'?[['record_collection','Registrar cobro'],['link_collection','Enlazar cobro existente']]:[['return','Registrar devolucion'],['link_return','Enlazar devolucion existente']])}${select('result-collection-'+row.id,'Cobro',[['','Selecciona'],...choices.map(c=>[c.id,c.effective_on+' · '+money(c.amount_cents)])])}${row.kind==='settlement'?input('result-allocate-'+row.id,'Aplicar al recibo','text','0,00'):input('result-free-'+row.id,'Saldo libre devuelto','text','0,00')+select('result-return-'+row.id,'Devolucion existente',[['','Selecciona'],...(s.facts?.items||[]).filter(x=>x.kind==='return').map(x=>[x.id,x.effective_on+' · '+money(x.amount_cents)])])+choices.flatMap(c=>c.allocations).map(a=>input('result-reverse-'+a.id,a.number+' · revertir','text','0,00')).join('')}</fieldset>`;}).join('');});
    const action=root().querySelector('[name=action]');if(action){const update=()=>{root().querySelector('[data-fact-field]').hidden=!action.value.startsWith('link_');root().querySelector('[data-outflow-field]').hidden=action.value!=='record_outflow';root().querySelector('[data-allocation-field]').hidden=action.value!=='record_collection';root().querySelector('[data-return-field]').hidden=action.value!=='return';root().querySelector('[data-refund-field]').hidden=action.value!=='refund';};action.onchange=update;update();}}
  async function guard(fn){const snapshot=s;if(s.busy)return;s.busy=true;root().setAttribute?.('aria-busy','true');try{await fn();}catch(e){if(s===snapshot){s.error=e.message;render();}}finally{snapshot.busy=false;if(s===snapshot)root().setAttribute?.('aria-busy','false');}}
  return {open,render,cancel:()=>{epoch++;}};
}
